### ISSUE TITLE
Scripts: compilation error on proxy catch block

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#1019]
Adding a catch to a proxy call triggers a compilation error:

![Screenshot 2023-09-18 at 11 24 59](https://github.com/NangoHQ/nango/assets/2560456/8d7ffc5d-3293-453b-abc5-012622e1d87d)
![Screenshot 2023-09-18 at 11 24 39](https://github.com/NangoHQ/nango/assets/2560456/9fcdfdd5-546f-49e5-8ff0-414d083873bc)

**Comment by hammadfauz** [comment]
To fix this, rewrite the code, as below.
```Typescript
try {
  const file = await nango.get({
    endpoint: endpoint
  });
} catch (err) {
  await nango.log("No file found, creating new file.");
  return null;
}
```
I can open a PR if needed.
