### ISSUE TITLE
Error not decoded from Github

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#1024]
There seems to be some problem outputting errors from Github:

<img width="1115" alt="Screenshot 2023-09-18 at 17 23 03" src="https://github.com/NangoHQ/nango/assets/2560456/7ff41d98-3e52-4fc0-93f1-daf886a73283">

**Comment by khaliqgant** [comment]
Dupe of https://github.com/NangoHQ/nango/issues/693
