### ISSUE TITLE
UI polish

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#1045]
issues

- I have medium size screen 1920x1080 but most of Nango screens have small horizontal scroll (latest Chrome on Windows 10)
- when adding integration, client id and secret should have autocomplete="off" to prevent autofill (I see this fixed in release notes, is cloud not updated yet?)
- when adding new connection, menu item "integration" become highlighted

wishes:
- show sdk version in cloud dashboard
- I would like to be able to change existing connection id ("rename") 

additions: 

Still auto-completing fields
![Image](https://github.com/NangoHQ/nango/assets/2560456/3998f0b4-7159-4e3f-a736-8108cdc5aa19)

Big info icon for api key integrations
![Image](https://github.com/NangoHQ/nango/assets/2560456/da1400ce-a2fe-47f8-b349-4bdb55edeae0)

There's significant dropoff on the integration creation page. A link to the relevant guide could help. 

![Image](https://github.com/NangoHQ/nango/assets/2560456/b4060ac1-9708-4264-b226-b3c1a6003789)

**Comment by khaliqgant** [comment]
Also listed in #996

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
