### ISSUE TITLE
Webhooks not working with self-signed certificates.

### ISSUE THREAD

**Issue by Simcon** [NangoHQ/nango#105]
I am running the Nango worker in a container and connecting to my app on the host via host.docker.internal.

The host app runs using self-signed SSL certs when debugging with Visual Studio. This is causing the webhook to fail with this message:

```
[ERROR] Webhook response error from https://host.docker.internal:5001/webhooks/nango for job 3 Sync 2: self-signed certificate (check debug logs for details).
```

To validate with curl, the following fails with the same error:

```
curl -i -X POST -H "content-type: application/json"  --data '{ "type":"HELLO" }' https://host.docker.internal:5001/webhooks/nango
```

But, if I add the ```--insecure``` flag it works.

One suggestion would be to add an "IGNORE_SSL" flag to the env vars and handle the same way to curl?

**Comment by Simcon** [comment]
A workaround for my case is to enable http redirection only in production:

```
if(env.IsProduction())
{
    app.UseHttpsRedirection();
}
```

Closing since this is good enough and let's not complicate the codebase unnecessarily!

**Comment by bastienbeurier** [comment]
Thank you for flagging this and investigating a fix!
