### ISSUE TITLE
`Add Sync` button should be just `Enable`

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#1093]
The `Add Sync` button is also used to add actions, so it should just be `Enable`.

<img width="1091" alt="Screenshot 2023-10-11 at 17 24 52" src="https://github.com/NangoHQ/nango/assets/2560456/a5f13332-2bc1-4d3b-81fa-79eb88151c5b">

**Comment by khaliqgant** [comment]
@bastienbeurier can you clarify the issue here? When an action is selected the button says "Add Action"

<img width="535" alt="image" src="https://github.com/NangoHQ/nango/assets/1724137/8048aa11-71e7-4798-aa49-37171118cfa0">

**Comment by bastienbeurier** [comment]
Sorry, I had not noticed this. It works well then! (closing)
