### ISSUE TITLE
EU Cloud

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#1099]
Process and store data in EU for customers who require it.

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker

**Comment by romankupkovic** [comment]
hey so is the EU based cloud available now?

**Comment by bastienbeurier** [comment]
@romankupkovic no, but we are now part of the [DPF program](https://www.nango.dev/product-updates/dpf-gdpr-compliant), which makes us compliant with EU rules without having an EU-based cloud.
