### ISSUE TITLE
Facebook integration: Can't load URL

### ISSUE THREAD

**Issue by f4th4n** [NangoHQ/nango#1107]
I tried to integrate with Facebook. Adding the integration is working fine. But when I tried to add new connection and click "Start OAuth flow" button I always get error "Can't load URL".

Here is the screenshot:

![Screenshot_2023-10-15_17-45-23](https://github.com/NangoHQ/nango/assets/10251361/bf4a1cf7-68f3-4b71-926a-f32b0a6dd0a2)

I already set App domains in facebook with these values: "api.nango.dev", "app.nango.dev" but still get error. What did I do wrong? How to fix the issue? Any response is appreciated, thanks.

**Comment by khaliqgant** [comment]
Hi @f4th4n I faced this same issue when I tried to register the incorrect type of facebook app. This ChatGPT guide actually helped point me in the right direction

-----

Creating OAuth credentials for Meta (formerly known as Facebook) involves registering an application with Meta's developer platform and configuring it to use OAuth for authentication. Here are the general steps to create OAuth credentials for Meta:

### 1. Register as a Developer
If you haven’t already, you need to create a developer account with Meta. 

- Go to [Meta Developers](https://developers.facebook.com/).
- Click on "Log In" if you're already registered or "Get Started" to create a new developer account.

### 2. Create a New App
Once you have a developer account, you can create a new app.

- Click on “My Apps” at the top right corner of the developer console.
- Click on “Create App”.
- Choose the type of app you're creating (e.g., For Everything Else) and give your app a name and email, then click on "Create App ID".

### 3. Set Up OAuth
You’ll need to set up OAuth and get your credentials.

- In your app’s dashboard, find the ‘Add a Product’ section.
- Click "Set Up" on the Facebook Login option.

### 4. Configure OAuth Settings
You'll need to configure the OAuth settings according to your application's requirements.

- Go to "Settings" under "Facebook Login" on the left sidebar.
- Fill in the “Valid OAuth Redirect URIs” field with the URI where you want to redirect users after authentication.
- Save the changes.

### 5. Get Your App ID and App Secret
Your App ID and App Secret, which serve as your OAuth credentials, can be found in the dashboard's main settings page.

- Click on “Settings” > “Basic” in the left sidebar.
- Here you can see your App ID and App Secret (click "Show" to reveal the App Secret, it will ask for password confirmation).

### 6. Make Your App Live
By default, your app is in development mode, and only you can log in to it. You need to make it live to allow access to other users.

- Go to “Settings” > “Basic”.
- Scroll down and toggle the switch from “In Development” to “Live”, or fill in the required fields to allow you to change the status to Live.

### Important Note
Make sure to read Meta’s platform policies and ensure that your application adheres to them to avoid any future issues with your app’s availability or functionality.

Now, you can use the App ID as the client ID and App Secret as the client secret in your application to integrate Meta's OAuth authentication.

**Comment by khaliqgant** [comment]
Going to close this but please reopen if you still see issues!
