### ISSUE TITLE
Consistent naming of fields in Nango APIs, docs & dashboard

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#1123]
The Nango platform has grown a lot in the last couple of months.
With this, some naming inconsistencies have appeared, that would be good to clean up.

- https://docs.nango.dev/api-reference/integration/get
   - `unique_key` should be `provider_config_key`
- https://docs.nango.dev/api-reference/connection/list
   - `provider` should be `provider_config_key`
- What the API calls `provider_config_key` we call `integration-id` in the docs and `Integration unique key` in the dashboard.
- What the API calls `provider` (except for the exception listed above) is called `Integration provider` in the dashboard

- `/sync/trigger` takes a `syncs` parameter, whilst `action/trigger` has an `action_name` parameter. Ideally, we either always append the `_name`, or we leave it out.

**Comment by rguldener** [comment]
Another one that caused some confusion/uncertainty:

https://docs.nango.dev/api-reference/connection/list exposes the internal id of the connection. Since it is not needed for any other API requests we might want to hide it, so there is no confusion on which id matters.

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
