### ISSUE TITLE
MS Team OAuth is not working(Missing authorization)

### ISSUE THREAD

**Issue by Abdul-Maajith** [NangoHQ/nango#1127]
Hello Nango Team:
I'm currently integrating MSTeams, following the documentation from nango and Microsoft! After setting up ClientId  and Client Secret  scopes and callback URL in Azure, when I try to Authenticate", I'm getting the following error:

`
Unkown error during the Oauth flow.
{
  "message": "Response Error: 401 Unauthorized",
  "name": "Error"
}
`
Here is the Log from Activity tab!

`
2023-10-17T17:54:50.465Z
Authorization URL request from the client
url: https://integrations-dev.askfulcrum.com/oauth/callback
hmacEnabled: false
2023-10-17T17:54:50.474Z
Redirecting to https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=d85798e4-d8d5-418d-98ca-000a8ee7eaed&redirect_uri=https%3A%2F%2Fintegrations-dev.askfulcrum.com%2Foauth%2Fcallback&scope=OnlineMeetingRecording.Read.All+OnlineMeetingTranscript.Read.All+User.Read+email+openid&state=2b000c60-6ce8-11ee-96a5-e766f3865d88&response_mode=query&prompt=consent for microsoft-teams (connection test-connection-id)
auth_mode: OAUTH2
url: https://integrations-dev.askfulcrum.com/oauth/callback
prompt: consent
scopes: OnlineMeetingRecording.Read.All OnlineMeetingTranscript.Read.All User.Read email openid
grant_type: authorization_code
response_mode: query
response_type: code
external_api_url: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=d85798e4-d8d5-418d-98ca-000a8ee7eaed&redirect_uri=https%3A%2F%2Fintegrations-dev.askfulcrum.com%2Foauth%2Fcallback&scope=OnlineMeetingRecording.Read.All+OnlineMeetingTranscript.Read.All+User.Read+email+openid&state=2b000c60-6ce8-11ee-96a5-e766f3865d88&response_mode=query&prompt=consent
2023-10-17T17:54:57.442Z
Received callback from microsoft-teams for connection test-connection-id
url: /oauth/callback?code=M.C104_BAY.2.d7ad6a0e-9e11-01aa-5656-c966cfc437ed&state=2b000c60-6ce8-11ee-96a5-e766f3865d88
state: 2b000c60-6ce8-11ee-96a5-e766f3865d88
2023-10-17T17:54:57.446Z
Initiating token request for microsoft-teams using microsoft-teams for the connection test-connection-id
code: M.C104_BAY.2.d7ad6a0e-9e11-01aa-5656-c966cfc437ed
scopes: OnlineMeetingRecording.Read.All,OnlineMeetingTranscript.Read.All,User.Read,email,openid
grant_type: authorization_code
token_params: [object Object]
basic_auth_enabled: false
2023-10-17T17:54:57.761Z
Unkown error during the Oauth flow.
{
  "message": "Response Error: 401 Unauthorized",
  "name": "Error"
}
`

Here, I'm attaching Images from Azure for References:!

![Screenshot 2023-10-17 192417](https://github.com/NangoHQ/nango/assets/77885682/10222cb3-207b-464c-b06b-2d44f0209b11)
![Screenshot 2023-10-17 192450](https://github.com/NangoHQ/nango/assets/77885682/1123973a-8d21-4495-9f52-e86155105c67)
![Screenshot 2023-10-17 192014](https://github.com/NangoHQ/nango/assets/77885682/f8811b1f-e600-4584-820e-7ca201b6634f)
![Screenshot 2023-10-17 192314](https://github.com/NangoHQ/nango/assets/77885682/e517d4ef-74d4-4a80-8414-edcd2af5568f)
![Screenshot 2023-10-17 192350](https://github.com/NangoHQ/nango/assets/77885682/0625205b-6dcf-4d14-bd3a-a6eb1705f722)

**Comment by Abdul-Maajith** [comment]
This is not a bug

**Comment by khaliqgant** [comment]
Copied the incorrect secret value.
