### ISSUE TITLE
Introduce rate-limits and proxy timeout

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#1160]
We should think of how we rate-limit different parts of the app. 
The most important thing to rate-limit is the auth part.
We should also introduce a tate-limit + timeout for proxy calls, since it's a free feature and could be abused.

We should have a way to increase the rate-limits of specific accounts.

**Comment by khaliqgant** [comment]
Relates to #1295 in that this will also probably leverage redis

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
