### ISSUE TITLE
Better transparency into nango proxy errors

### ISSUE THREAD

**Issue by khaliqgant** [NangoHQ/nango#1173]
From this [thread](https://nango-community.slack.com/archives/C04ABR352H0/p1697799838090539) 

> I was asking whether there was a way to retrieve that info in the proxied request (I don't know if it carries some other issues though), because right now developers have to check activity logs to see what went wrong (and I reckon that in a production environment this might not be ideal)

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
