### ISSUE TITLE
Same sentence twice in the Quickstart page

### ISSUE THREAD

**Issue by ShriKaranHanda** [NangoHQ/nango#1195]
Same sentence twice in [Quickstart](https://docs.nango.dev/quickstart#sync-data-from-an-api-github-issues)

![Screenshot from 2023-10-27 20-24-14](https://github.com/NangoHQ/nango/assets/79533543/8d1f7b62-7c09-422c-8ab1-dbb27049b164)

Let me know if this is valid issue and I'll create a quick PR to fix this

**Comment by bastienbeurier** [comment]
Fixed, thank you!
