### ISSUE TITLE
Unified routes and nango.yaml retool

### ISSUE THREAD

**Issue by khaliqgant** [NangoHQ/nango#1250]
See [spec](https://www.notion.so/nangohq/Nov-2023-Interface-Revamp-4755d2717a0142dfb9a447e37eb91a5e?pvs=4) & builds on #1188

**Comment by bastienbeurier** [comment]
@khaliqgant could #1171 be tackled as part of the same effort or better to separate?

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
