### ISSUE TITLE
Add support for Klaviyo API

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#1262]
We got a request for Klaviyo API support.
Looks like it is API key based:

- https://developers.klaviyo.com/en/docs/retrieve_api_credentials
- https://developers.klaviyo.com/en/docs/authenticate_

I think for now only the private API needs to be supported. The public one is mostly for ingesting user events on pages.

**Comment by grjan7** [comment]
Added support for Klaviyo API and made PR (https://github.com/NangoHQ/nango/pull/1236).

**Comment by grjan7** [comment]
This issue can be closed now as merging PR ([#1236](https://github.com/NangoHQ/nango/pull/1236)) solved this.
