### ISSUE TITLE
CLI dryrun command: Make setMetadata side effect free

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#1298]
`nango dryrun` is already almost entirely side effect free today.

But calling `nango.setMetadata(data)` **does** actually save the metadata to the connection on the server.

If you want to avoid this, comment out any `nango.setMetadata` calls when using dryrun and instead stub metadata with the CLI command:

```
nango dryrun -m {} test-sync test-connection-id
```

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
