### ISSUE TITLE
API endpoint to reset a sync/trigger a full refresh

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#1300]
Currently Nango doesn't offer an endpoint to reset a sync & do a full refresh (without deleting a connection).

It would be good to have such an endpoint, which:
- Resets last sync date
- Probably also removes all previously synced data from the cache

Have a use-case for this? PLease leave a comment with some details and which functionality would be helpful for you.

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
