### ISSUE TITLE
Add support for Okta (service APIs)

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#1367]
Goal: Integrate with Okta to fetch employees and manage which employee has access to which app.
For example, the apps API: https://developer.okta.com/docs/reference/api/apps/

My understanding is this is covered by the Okta Managmenet API endpoints, which are accessed with API service integrations: https://developer.okta.com/docs/guides/oin-api-service-overview/

Okta calls their integrations marketplace the Okta integration network: https://developer.okta.com/docs/guides/okta-integration-network/

**Comment by hassan254-prog** [comment]
Hi @rguldener , I have successfully implemented the above on #1411 . The [Core Okta API](https://developer.okta.com/docs/reference/core-okta-api/)  gives access to resources that you had mentioned above.
