### ISSUE TITLE
Add support for Blackbaud SKY API

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#1400]
For a new customer we should add support for Blackbaud SKY API (which covers all Blackbaud products).
Documentation of the Oauth flow is here: https://developer.blackbaud.com/skyapi/docs/authorization/auth-code-flow/confidential-application

From what I could tell there is a self-service signup flow for dev accounts, so we should be able to test the flow.

**Comment by hassan254-prog** [comment]
Hi @rguldener after self-service signup flow for dev accounts, you will need to request access for “SKY Developer Cohort” environment after which upon review by the team you will receive an invite. After accepting the invitation, you should have access to an instance of Raiser's Edge NXT that you can use for testing.

#1409

**Comment by rguldener** [comment]
Thanks @hassan254-prog 🙌

**Comment by bastienbeurier** [comment]
Resolved by #1409
