### ISSUE TITLE
Getting started in the readme for contributions and local setup

### ISSUE THREAD

**Issue by thebluespecs** [NangoHQ/nango#1412]
I do not see any getting started in the read me for local setup/developers guide of the application. Apologies If I missed something.

https://docs.nango.dev/contribute
Is this the doc?

**Comment by bastienbeurier** [comment]
These are indeed the contribution docs with local setup instructions. To start nango locally, you just need to run `docker compose up` (cf. this [section](https://docs.nango.dev/contribute#step-2-test-your-new-provider)).

We are also preparing a new version of the docs with more details on the local setup.
