### ISSUE TITLE
Add support for ServiceNow REST API

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#1416]
ServiceNow uses OAuth 2 for their REST API: https://docs.servicenow.com/bundle/vancouver-platform-security/page/administer/security/concept/c_OAuthApplications.html

We got some requests for it, would be great to add support if it does not require platform changes (I did not check in-depth yet).
We only need to implement the authorization_code grant for now.

**Comment by hassan254-prog** [comment]
Hi @rguldener , for a simpler understanding, one can have a look at the following thread from [ServiceNow Knowledge base](https://support.servicenow.com/kb?id=kb_article_view&sysparm_article=KB0778194).
