### ISSUE TITLE
Strava and Garmin Connect

### ISSUE THREAD

**Issue by Dave-DigiMim** [NangoHQ/nango#1521]
Any chance  of getting these APIs linked?

**Comment by bastienbeurier** [comment]
Hi @Dave-DigiMim, [Strava](https://docs.nango.dev/integrations/all/strava) is already available. 

For Garmin, it requires an [approval](https://www.garmin.com/en-US/forms/GarminConnectDeveloperAccess/) to get a developer account. If you manage to be approved and willing to share the account, we would be happy to add support fast!

**Comment by Dave-DigiMim** [comment]
I will try the strava, Garmin connect is a real pain as they keep changing the rules , I currently use this package..
https://github.com/petergardfjall/garminexport
