### ISSUE TITLE
Add AWS integration

### ISSUE THREAD

**Issue by shanzack** [NangoHQ/nango#1539]
Looks like AWS is currently not integrated.

**Comment by bastienbeurier** [comment]
@shanzack we do support the [Amazon API](https://docs.nango.dev/integrations/all/amazon). Is that not what you need?

**Comment by shanzack** [comment]
@bastienbeurier No! Thats the API for amazon.com (the shopping website), it does not provide auth to AWS (Amazon Web Services).
CC @rguldener

**Comment by bastienbeurier** [comment]
Sorry for the confusion, and also I didn't mean to close this issue. We'll implement it and get back.
