### ISSUE TITLE
connectionCreatedHook run twice when using api to create connection

### ISSUE THREAD

**Issue by ericpromax** [NangoHQ/nango#1592]
I found `connectionCreatedHook` run twice when using api to create connection.
The first call 
for oauth connection:
https://github.com/NangoHQ/nango/blob/e22bd0c7993c5b5a9905682fb94188895b5c5d60/packages/shared/lib/services/connection.service.ts#L223
for api connection:
https://github.com/NangoHQ/nango/blob/e22bd0c7993c5b5a9905682fb94188895b5c5d60/packages/shared/lib/services/connection.service.ts#L257
The second call:
https://github.com/NangoHQ/nango/blob/e22bd0c7993c5b5a9905682fb94188895b5c5d60/packages/server/lib/controllers/connection.controller.ts#L695

I am willing to create a PR to resolve this issue, but I'm uncertain about which one should be deleted and which should be retained.

**Comment by khaliqgant** [comment]
Thanks for this @WhyNotEric! The `connectionCreated` hook in the `connection.controller` only runs if `runHook` is set to true.

```if (updatedConnection && updatedConnection.id && runHook) {
                await connectionCreatedHook(
                    {
                        id: updatedConnection.id,
                        connection_id,
                        provider_config_key,
                        environment_id: environmentId,
                        auth_mode: template.auth_mode,
                        operation: updatedConnection?.operation || AuthOperation.UNKNOWN
                    },
                    provider,
                    null
                );
            }
```

`runHook` is [initialized as false](https://github.com/NangoHQ/nango/blob/e22bd0c7993c5b5a9905682fb94188895b5c5d60/packages/server/lib/controllers/connection.controller.ts#L523) and is only set to [true for importing an App](https://github.com/NangoHQ/nango/blob/e22bd0c7993c5b5a9905682fb94188895b5c5d60/packages/server/lib/controllers/connection.controller.ts#L687) so the connectionCreated hook only runs once for everything else.

**Comment by ericpromax** [comment]
Thanks khaliqgant. I think it's fixed now. I saw this bug last week and the `runHook` had not been submitted. I just synced my codebase, now every thing is right.

**Comment by khaliqgant** [comment]
Got it, thanks @WhyNotEric. This bug was caught last week and fixed with this PR: https://github.com/NangoHQ/nango/pull/1542
