### ISSUE TITLE
Pagination: Support cursors passed in response headers

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#17]
The Shopify Admin REST API uses cursors for pagination, but these are sent to the client as part of the response headers (instead of the JSON body): https://shopify.dev/api/usage/pagination-rest

A real world example is the orders endpoint: https://shopify.dev/api/admin-rest/2022-10/resources/order#get-orders?since-id=123

**Comment by rguldener** [comment]
The same is true for the Gitlab API: https://docs.gitlab.com/ee/api/index.html#keyset-based-pagination
Some endpoints are still on an older pagesize + page integer based pagination (as requested in #16)

**Comment by bastienbeurier** [comment]
Fixed as part of https://github.com/NangoHQ/nango/commit/d672a68a1012b505f87760843c11b8cb7139a5d7
