### ISSUE TITLE
Convert @nangohq/node to @nangohq/js -- remove node dependencies

### ISSUE THREAD

**Issue by lawrencecchen** [NangoHQ/nango#2068]
I'm using Cloudflare Workers/Durable Objects and can't use the nango client libraries due to axios and other uses of `node:crypto`. I've been using a fetch wrapper instead:

```ts
async function nangoProxy(input: ProxyConfiguration) {
  return await fetch(`https://api.nango.dev/proxy/${input.endpoint}`, {
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      Authorization: `Bearer ${env.NANGO_SECRET_KEY}`,
      "Provider-Config-Key": input.providerConfigKey ?? "",
      "Connection-Id": input.connectionId ?? "",
    },
    body: JSON.stringify(input.data),
    method: input.method,
  }).then((r) => r.json());
}
```

It would be great if the official library becomes edge compatible as well.

**Comment by bastienbeurier** [comment]
Thanks for submitting this. Most people consume this SDK from their backend, but I understand that it's different in your case. Unfortunately we don't have a timeline to support this, but we will send an update when we do.

**Comment by lawrencecchen** [comment]
> Most people consume this SDK from their backend

Just to clarify, I'm using nango from my cloudflare workers backend which is missing some node builtins.

But understand that bandwidth is limited -- would a PR here be accepted?

**Comment by bastienbeurier** [comment]
Got it. 

Thanks for proposing to contribute, it's much appreciated. 

What would be the nature of the contribution?
