### ISSUE TITLE
Add X integration

### ISSUE THREAD

**Issue by vr-varad** [NangoHQ/nango#2150]
How about integrating X? There is no integration for Twitter.
https://developer.twitter.com/en/docs

**Comment by bastienbeurier** [comment]
We do have Twitter supported! [https://docs.nango.dev/integrations/all/twitter](https://docs.nango.dev/integrations/all/twitter)<br><br>Or are you looking for integration template to sync specific Twitter objects?

**Comment by TorstenSchmickler** [comment]
Why is this still open?

**Comment by TBonnin** [comment]
No reason indeed. Closing now.
