### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by MikhailZolikoff-EverTrue** [NangoHQ/nango#2197]
Path: /reference/api/sync/update-connection-frequency

What are all of the options for "frequency"? They are listed here. 

Thanks!

**Comment by bastienbeurier** [comment]
We are using https://github.com/vercel/ms for frequency notations. The minimum frequency is 5 minutes.

Here are example notations: 
'2 days'
'1d'
'2.5 hrs'
'1m'
'1y'

**Comment by bastienbeurier** [comment]
We just updated the docs to add this information! https://github.com/NangoHQ/nango/pull/2203
