### ISSUE TITLE
Please add config to pass HTTP_PROXY and HTTPS_PROXY so that requests to the third party integrations go via this proxy

### ISSUE THREAD

**Issue by mithlesh135** [NangoHQ/nango#2233]
const axios = require('axios');
const HttpProxyAgent = require('http-proxy-agent');
const HttpsProxyAgent = require('https-proxy-agent');

// Get the proxy URL from the environment variables
const proxyHttpUrl = process.env.HTTP_PROXY || process.env.http_proxy;
const proxyHttpsUrl = process.env.HTTPS_PROXY || process.env.https_proxy;

// Create the appropriate proxy agent
const httpAgent = proxyHttpUrl ? new HttpProxyAgent(proxyHttpUrl) : undefined;
const httpsAgent = proxyHttpsUrl ? new HttpsProxyAgent(proxyHttpsUrl) : undefined;

**Comment by khaliqgant** [comment]
Will let you know once this is deployed, thanks for your contribution.
