### ISSUE TITLE
CONTRIBUTING.md is missing steps or assuming them

### ISSUE THREAD

**Issue by Pyloris** [NangoHQ/nango#2239]
Problem 1:
In the CONTRIBUTING.md file, inside the DEVELOP LOCALLY Section, dependencies are being installed only in the root of the project. It causes errors on frontend as its dependencies are not installed.

Problem 2:
In the Run Integrations section of the file, it instructs to include `NANGO_SECRET_KEY_DEV` and `NANGO_HOSTPORT`. I think both should have steps on how to get their values. Especially the Nango_Hostport, which i personally took that it meant PORT on which nango is running locally. But then i figured it was HOST:PORT.

FIX:
There should be another step to install dependencies of the frontend (in the folder /packages/frontend/)
```
# in the /packages/frontend/ folder execute
npm i
```
```
# NANGO_SECRET_KEY_DEV can be found in Environment settings on nango dashboard
# NANGO_HOSTPORT is the URL on which nango instance is running to which we want to deploy our integrations.

**Comment by bodinsamuel** [comment]
Resolved in PR 👍🏻
