### ISSUE TITLE
Headers not supported when sending an email using google-mail integration

### ISSUE THREAD

**Issue by Pyloris** [NangoHQ/nango#2291]
Problem:
If we want to send an email that contains HTML body, we cannot specify necessary headers so that email gets rendered properly.

Solution:
Add support for headers in the google-mail integration so that we can specify custom headers.

**Comment by bastienbeurier** [comment]
Are you using the [proxy](https://docs.nango.dev/understand/concepts/proxy) or [integration scripts](https://docs.nango.dev/understand/concepts/scripts)? In both case you should be able to specify headers in your HTTP requests to Gmail. Or maybe I didn't understand your question?

**Comment by Pyloris** [comment]
@bastienbeurier actually i contributed an action script and it did not support adding headers to an email when sending it via that script.
So to support it, i have opened the above PR. please review it.
