### ISSUE TITLE
Store Nango-related data in any Postgres database & schema

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#25]
We current store all Nango-related data in the default public schema of Postgres. We should use a separate schema for clarity and make it configurable.

**Comment by cpursley** [comment]
It would be nice if schema as user-configurable.

**Comment by bastienbeurier** [comment]
@cpursley indeed, just edited issue.

**Comment by bastienbeurier** [comment]
This is addressed by https://github.com/NangoHQ/nango/commit/96687e0f5016f1d6e161a7877e0355064a3ccd0c. Here is the documentation for it -> https://github.com/NangoHQ/nango/commit/96687e0f5016f1d6e161a7877e0355064a3ccd0c
