### ISSUE TITLE
"Region is missing" when I run "sample-app" on self-hosting server

### ISSUE THREAD

**Issue by hunghuynh1011** [NangoHQ/nango#2521]
Hi, I just deploy nango server on my pc locally, and I would like to run sample: NangoHQ/sample-app. However, I got the issue when I run comment: "nango deploy dev": 

**- In console: nango deploy dev**
Compiled "/home/uevn/workspace/hungh/nango/sample-app/nango-integrations/slack/syncs/users.ts" successfully
Compiled "/home/uevn/workspace/hungh/nango/sample-app/nango-integrations/slack/actions/send-message.ts" successfully
Sync "users" is new. Nango will start syncing the corresponding data for 1 existing connections.
Error deploying the scripts with the following error: undefined

**- In console of Nange local server:** 
nango-server  | node:internal/process/promises:289
nango-server  |             triggerUncaughtException(err, true /* fromPromise */);
nango-server  |             ^
nango-server  |
nango-server  | Error: Region is missing
nango-server  |     at default (/usr/nango-server/src/node_modules/@smithy/config-resolver/dist-cjs/index.js:117:11)
nango-server  |     at /usr/nango-server/src/node_modules/@smithy/node-config-provider/dist-cjs/index.js:90:104
nango-server  |     at /usr/nango-server/src/node_modules/@smithy/property-provider/dist-cjs/index.js:97:33
nango-server  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Could you please give me some suggestions?

**Comment by bodinsamuel** [comment]
Hi,
`nango-server` image does not support script and syncs, you should try sample-app with the cloud version 👌🏻
