### ISSUE TITLE
Podium integration

### ISSUE THREAD

**Issue by lawrencecchen** [NangoHQ/nango#2588]
https://docs.podium.com/docs/oauth

**Comment by rguldener** [comment]
Hi @lawrencecchen Thanks for the request.

To test the integration, we will need:
- client id & secret
- A podium account

It seems Podium doesn't offer self-service signup for developers: https://docs.google.com/forms/d/e/1FAIpQLSegNSRGdfu62ooYMpLpQJOWOYkfH1a47YT0tChuZ2gPbREUJA/viewform

I also cannot find a self-service signup option for the application itself.

Do you have credentials we can use for testing?
Feel free to email me or send it to me on a DM on the Slack community: https://nango.dev/slack

**Comment by hassan254-prog** [comment]
Completed with the following [PR](https://github.com/NangoHQ/nango/pull/2601)
