### ISSUE TITLE
CodeClimate integration

### ISSUE THREAD

**Issue by MichaelHinrichs** [NangoHQ/nango#2613]
https://developer.codeclimate.com/#overview

**Comment by bastienbeurier** [comment]
@hassan254-prog could you tackle this one please and track it on Linear?

**Comment by hassan254-prog** [comment]
@bastienbeurier, of course. Thank you for pinging me on this.

**Comment by hassan254-prog** [comment]
Completed with the following [PR](https://github.com/NangoHQ/nango/pull/2625).
