### ISSUE TITLE
1-click deployment solution on Render

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#269]
The previous iteration of Pizzly had a 1-click deployment option to Heroku. A new limitation is that Heroku no longer has a free-tier.

Similarly to what has been done to Nango ([here](https://github.com/NangoHQ/nango/commit/1129aacfe18fb9d1c3bd5086896283bd54343e24)), we should create a blueprint to simply deploy Pizzly on Render for free.

**Comment by mtzfactory** [comment]
That would be fantastic... I'm new to Render and having some troubles trying to deploy this app there...

**Comment by bastienbeurier** [comment]
@mtzfactory noted!

In the meantime, we have simple instructions to deploy Nango (which contains Pizzly) on AWS, GCP and DigitalOcean in <5mins -> https://docs.nango.dev/category/deploy-nango-open-source

Happy to assist you in setting this up if you are interested!

**Comment by Pranav2612000** [comment]
Nango seems amazing. I'll like to contribute to the project and work on this task. Is this project open to external contributors?

**Comment by bastienbeurier** [comment]
Hi Pranav, you are welcome to contribute! Thanks a lot for joining our community 🙌

Having a quick deploy option for Render (and maybe Heroku later) would be great. 

We do have a Render template for internal purposes already, here it is in case it speeds you up to build one inside the NangoHQ/nango repo -> https://github.com/NangoHQ/nango-render

**Comment by Pranav2612000** [comment]
Thank you. I'll take a look at this and have a PR ready soon. Is commenting here the best way to ask questions if I need help with something?

**Comment by bastienbeurier** [comment]
Yes, here is great. Or feel free to ping me directly on the [Slack community](https://nango.dev/slack).
