### ISSUE TITLE
Write tests for Nango

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#273]
The is not tests in Pizzly at the moment. We should have tests integrated in our CI, similarly to the [previous iteration of Pizzly](https://github.com/NangoHQ/Pizzly/tree/2c2e999d505058c1114611bc26f9c9a4243ee435).

Improvements: 
- Test all OAuth 2 integrations
- Test all OAuth 1 integrations
- Integrate in CI

Unit tests for: 
- Encryption
- Authentication
- Special flows (e.g. braintree, figma)
- Webapp
- Frontend SDK (WebSocket)
- Backend SDKs
- Individual server routes
- Connection Metadata
- Connection Configuration

**Comment by khaliqgant** [comment]
This will be ongoing but the initial effort has been done here. Will reference this issue with continued improvements.

**Comment by khaliqgant** [comment]
Integration tests: https://medium.com/@ismailkuruca/how-to-effectively-write-integration-tests-with-nodejs-knex-postgres-bcaa60022080
