### ISSUE TITLE
Zoom OAuth trigger doesn't work if requesting multiple scopes

### ISSUE THREAD

**Issue by sidvenu** [NangoHQ/nango#2793]
Hey folks, I have a test app on Zoom (OAuth "general" app) that needs 2 scopes: `cloud_recording:read:list_user_recordings:admin` and `cloud_recording:read:list_recording_files:admin`. I have set up the same in Nango:
<img width="837" alt="image" src="https://github.com/user-attachments/assets/477d1973-a20b-484b-8ee9-477d184d07a1">

However, it runs into the following error:
<img width="483" alt="image" src="https://github.com/user-attachments/assets/9aeb8dc3-bb9e-48c6-bd68-f3f1d3fdf83c">

However, it works perfectly fine if I just request one scope or the other. I am able to add the connection and perform API requests using them.

**Comment by khaliqgant** [comment]
Hi @sidvenu are you the admin user on your account?

> Account-level apps (apps with admin) scopes must be authorized by a user with the corresponding account-level permissions. An app requesting the report:read:admin scope, for example, would need the admin-level Role Permissions to view Usage reports. See [Using role management](https://support.zoom.us/hc/en-us/articles/115001078646-Using-role-management?_gl=1*k1r65g*_gcl_au*MjAxNTA0NDAyMC4xNzI2MTU4NTQ1*_ga*ODM3MDExMjUxLjE3MDc0NjIxMjA.*_ga_L8TBF28DDX*MTcyNzc4NzQwNi4xMC4xLjE3Mjc3OTA0MzkuMC4wLjA.) for more information.

Which leads to https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0064983&_gl=1*ukdb8u*_gcl_au*MjAxNTA0NDAyMC4xNzI2MTU4NTQ1*_ga*ODM3MDExMjUxLjE3MDc0NjIxMjA.*_ga_L8TBF28DDX*MTcyNzc4NzQwNi4xMC4xLjE3Mjc3OTA0MzkuMC4wLjA.

**Comment by sidvenu** [comment]
@khaliqgant i am. Notice that it works when I use the scopes one by one. If I use just `cloud_recording:read:list_user_recordings:admin` OR `cloud_recording:read:list_recording_files:admin`, everything works perfectly.

**Comment by TBonnin** [comment]
hi @sidvenu can you share with us your zoom app access settings. (in DM in Slack if you prefer)

<img width="1086" alt="Screenshot 2024-10-01 at 15 17 30" src="https://github.com/user-attachments/assets/4777ce0f-d373-4279-9335-e3ce07c1c437">
