### ISSUE TITLE
The ability to request scopes when calling `nango.auth()`

### ISSUE THREAD

**Issue by matt-aitken** [NangoHQ/nango#287]
For our use case, we want to create our provider OAuth apps with generous scopes, and then depending on our user's API calls  we want to request the correct subset of the overall scopes.

## GitHub API example
- We create a GitHub OAuth app with all scopes (or all reasonable scopes), and add it to Pizzly using the CLI
- In our product a user wants to call the GitHub API to modify their private repo
- We display the "Connect to GitHub" button and when they press it, it will request auth from Pizzly with just the `repo` scope

# Suggested implementation
- The existing Pizzly configs would remain the same, with the `auth_scopes` column in tact.
- When requesting auth from the frontend you would pass in an optional config param like this: `pizzly.auth("github", "<connectionId>", { "scopes": ["repo"] })`

**Comment by bastienbeurier** [comment]
Thank you for submitting @matt-aitken . 

For context, we currently keep track of scopes at the Provider Configuration level (vs. Connection level).

Just to make sure I understand: 
- each Connection would have different scopes for a single Provider Configuration?
- how would you keep track of which Connection has which scopes?
- if a user later wants more scopes, would you use a new Connection for the same user?

**Comment by bastienbeurier** [comment]
One way I could see it working with the current system is: 
- you have multiple Provider Configurations for Github with different scopes
- based on the scopes required for each user, you create a Connection for the relevant Provider Configuration
- as users request new scopes, you create a new Connection for them for the relevant Provider Configuration (which has more scopes)

**Comment by matt-aitken** [comment]
I think some more context of what we're trying to achieve might help. We're creating a way for developers to easily subscribing to APIs (webhooks) and then call APIs to create automation workflows. Think Zapier but written in your codebase. There are some examples on this page: https://trigger.dev

Our experience has been that developers are very worried about using broad scopes, so we'd like really fine controls over them. We were hoping that for each workflow we would generate the scopes required for each API and then allow you to just get those.

If we do that it will require creating too many OAuth apps I think for it to be practical. Unless we created the OAuth apps dynamically from code but I doubt many (any?) APIs support doing that.

> each Connection would have different scopes for a single Provider Configuration?
Yes exactly 👍 

> how would you keep track of which Connection has which scopes?
Maybe add a column to the `_pizzly_connections` table called `scopes`. Or perhaps that isn't needed based on GitHub's `credentials` column value:
```json
{
  "type":"OAUTH2",
  "accessToken":"<access_token>",
  "raw":{
    "access_token":"<access_token>",
    "token_type":"bearer",
    "scope":"public_repo"
  }
}
```
There's already a scope there, but not sure how universal that is across APIs.

**Comment by rguldener** [comment]
Regarding this:
> Or perhaps that isn't needed based on GitHub's credentials column value:
> [...]
> There's already a scope there, but not sure how universal that is across APIs.

Based on what I have seen across a dozen different OAuth providers or so this is not really standard behaviour we can rely on. Many include the scopes back in the reply, but by far not all of them.

Another use case that might make sense to consider in the context of a possible API change here:
Some APIs allow you to customize the behaviour of the OAuth flow by passing additional parameters in the Authorize step (and some in the token request step). A good example is [Google's OAuth flow](https://developers.google.com/identity/protocols/oauth2/web-server#creatingclient), e.g. their `prompt` and `access_type` parameters, which many other OAuth flows also use.

Currently we deal with this by adding sensible defaults in the templates for these. For Google for instance we set `pompt` to `consent` and `access_type` to `offline`. The defaults are probably good for 90% of the cases, but I could see a need in some cases to override the (authorization) params for a specific flow.

This is probably out of scope here but wanted to raise it so it can be considered when we think about the API for customizing configs per OAuth flow.

**Comment by bastienbeurier** [comment]
What about something like this: 
- Default scopes need to be specified (and stored) at the Provider Configuration level
- If no scope param is passed in the `pizzly.auth()` call, the Provider Configuration scopes are used
- If scopes are passed in the `pizzly.auth()` call, they have precedence (and we ignore Provider Configuration scopes)
- Final scopes used are stored at the Connection level

**Comment by matt-aitken** [comment]
@bastienbeurier I like that 👍 

> Currently we deal with this by adding sensible defaults in the templates for these. For Google for instance we set pompt to consent and access_type to offline. The defaults are probably good for 90% of the cases, but I could see a need in some cases to override the (authorization) params for a specific flow.

That's really interesting, I didn't know about this. Having these as other keys in the config params could be good when calling `auth()`.

**Comment by rguldener** [comment]
@bastienbeurier Sounds like a good solution. 👍

An API for `auth()` could then just take a config object as third parameter. This way we can start with scopes and add support for other config overrides per flow in the future.

**Comment by bastienbeurier** [comment]
@matt-aitken are you still interested in doing this? 

You would need to add an optional `oauth_scopes` field to the `Connection` model, and use it to overwrite the `oauth_scopes` field value from the `ProviderConfig` model when establishing the connection. Finally, you want to edit the frontend SDK to support this in a `config` optional parameter.

**Comment by matt-aitken** [comment]
Yep I'm still happy to do it but it will have to be in the new year as I'm currently building other parts of the product. Our first version will use very broad scopes and then we'll add specific scopes later, which will require this.

**Comment by bastienbeurier** [comment]
Sounds good :)

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker

**Comment by yksolanki9** [comment]
Hey @bastienbeurier, our use case also involves requesting scope per connection. Are there any plans to support this feature?

**Comment by bastienbeurier** [comment]
you can configure some custom authorization URL params [here](https://docs.nango.dev/reference/api/connect/sessions/create#body-integrations-config-defaults-key-authorization-params), including override scopes per connection.
