### ISSUE TITLE
Invalid query params in endpoint /connection?connectionId

### ISSUE THREAD

**Issue by pedroallenrevez** [NangoHQ/nango#2920]
```
"error":{"code":"invalid_query_params","errors":[{"code":"unrecognized_keys","message":"Unrecognized key(s) in object: 'connectionId'","path":[]}]}}
```

I used the example straight out of the documentation here:
https://docs.nango.dev/reference/api/connection/list

This seemed to be working before.

**Comment by bodinsamuel** [comment]
Fixing that 👌🏻

**Comment by keedyc** [comment]
I get the same error as of this morning.
