### ISSUE TITLE
Add a healthcheck url

### ISSUE THREAD

**Issue by matt-aitken** [NangoHQ/nango#296]
Add a simple GET `/healthcheck` endpoint
- It checks it can connect to the database
- If it can it returns a 200
- It does not require any authentication information

This is useful when deploying because services like fly.io will automatically take down servers that fail the health check and spin up new ones. Also, when deploying an ECS task you need a health check

**Comment by bastienbeurier** [comment]
Indeed, thanks for pointing this out. Lmk if you need assistance with this.

**Comment by aarishmkhan** [comment]
Hey, I can work on this issue. Please assign this issue to me

**Comment by bastienbeurier** [comment]
Thank you @aarishmkhan !

**Comment by bastienbeurier** [comment]
Solved by https://github.com/NangoHQ/nango/commit/a0b72cdb4c3fb8c01c2d4532eca0f263a5222f88
