### ISSUE TITLE
How can I make it work with Google Sheets?

### ISSUE THREAD

**Issue by mtzfactory** [NangoHQ/nango#297]
I would like use **Pizzly** with Google Sheets, but can't find the integration in the [providers](https://github.com/NangoHQ/Pizzly/blob/master/packages/auth/providers.yaml)...

I just found this article about "[How to integrate with the Google Sheets API, in 5 minutes](https://dev.to/bearer/how-to-integrate-with-the-google-sheets-api-in-2-minutes-569o)", but seems to refer to **Pizzly v1**

I would appreciate any help...

**Comment by bastienbeurier** [comment]
Any news on this? 

Also, it looks like you can use our other Google templates for this (cf. Community [thread](https://nango-community.slack.com/archives/C04JKLRMBM5/p1673855181194039)).

**Comment by bastienbeurier** [comment]
@mtzfactory just checked that it works with GSheet

Also added a specific `google-sheet` provider for clarity (https://github.com/NangoHQ/nango/commit/e506c9990666d0e006dd92908c401739749c6e77). 

So now you can create a config for GSheet with the CLI:
```
npx nango config:create gsheet google-sheet <APP-ID> <APP-SECRET> https://www.googleapis.com/auth/spreadsheets
```

If you haven't used Nango/Pizzly before, I would just go through the [Quickstart](https://docs.nango.dev/quickstart). The rest should be the same.

I tested the endpoint: 
```
curl https://sheets.googleapis.com/v4/spreadsheets/<sheet-id> -H "Accept: application/json" -H "Authorization: Bearer <fresh-access-token-fetched-with-nango>"
```

If you find other gotchas, please feel free share them with the community at: https://docs.nango.dev/providers/google-sheet
