### ISSUE TITLE
Issue with npm Workspace Resolution - No workspaces found

### ISSUE THREAD

**Issue by Godlinmilan** [NangoHQ/nango#2986]
I am using a docker-compose file for self-hosting Nango, but I encountered an issue @nangohq/connect-ui serve: unsafe for the Nango server. The error message indicates that no workspaces were found for @nangohq/connect-ui.
![Screenshot from 2024-11-14 13-35-32](https://github.com/user-attachments/assets/56fbe68b-9654-44be-938d-2cc59b3e85e5)

**Comment by bodinsamuel** [comment]
Hey, indeed there is an issue here, thanks for reporting. 
Fixing that asap 👌🏻
