### ISSUE TITLE
OAuth popup window blocked on Safari

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#302]
Detected by @matt-aitken 

https://user-images.githubusercontent.com/2560456/216574382-8c559887-69f5-41d1-934a-2784fa6f447f.mp4

**Comment by Pranav2612000** [comment]
It's opening for me on Safari ( gif attached )

![Kapture 2023-02-18 at 20 44 44](https://user-images.githubusercontent.com/20909078/219873522-9f0b6acd-57af-4e09-a3a0-f76d51e7e937.gif)

**Comment by rguldener** [comment]
Could reproduce this issue locally and on Nango Cloud with Safari Version 16.4 (18615.1.26.11.22).
Initial fix in the commit above, it looks like there were two issues:
- Safari prevents popups from async functions, so the workaround of Timm is required (create window before async things happen)
- Safari return `null` on `window.open` if the `noopener` flag is set (despite the window opening properly). This prevents us from setting the location/href later on. I disabled this flag.

Works locally on chrome and safari for me but this needs more extensive testing (especially also with Braintree/flows that force noopener from their side) before we push it to prod.
