### ISSUE TITLE
Missing "nango" in the third command on the revised Quickstart doc

### ISSUE THREAD

**Issue by duckdotapk** [NangoHQ/nango#303]
You happened to update this doc while I was looking at it and I noticed that the third command is missing the `nango`:

```
npx token:get 1 github-dev
```

**Comment by duckdotapk** [comment]
Going to tag @bastienbeurier since you updated the doc.

**Comment by bastienbeurier** [comment]
Thanks a lot for flagging! Should be fixed now.
