### ISSUE TITLE
Add MySQL support

### ISSUE THREAD

**Issue by derekperkins** [NangoHQ/nango#305]
It would be awesome to make the database agnostic so you could use MySQL (or even sqlite). It looks like you are using knex.js as a SQL builder, so hopefully that wouldn't require too much work

**Comment by rguldener** [comment]
Thanks for the suggestion derek!
Currently we don't have any plans to support other databases, but if there is strong demand from the community or contributors want to add it we are open to it :)

**Comment by bastienbeurier** [comment]
This is not likely to happen anytime soon, mostly because the preferred way to access the data is with SDKs, the REST API and webhooks.
