### ISSUE TITLE
API request: Microsoft outlook

### ISSUE THREAD

**Issue by jhoetter** [NangoHQ/nango#309]
Really interesting approach, nango team :)

We're currently planning to integrate with Microsoft for Outlook (i.e. email access), but it is very tedious. Is there any chance you have planned to build an integration for this?

**Comment by rguldener** [comment]
Hi @jhoetter,

I just checked and it looks like Outlook uses the Microsoft Graph API: https://learn.microsoft.com/en-us/outlook/rest/get-started
The graph API covers a ton of different Microsoft services under the same Authentication and we already support it. The template is called `microsoft-teams` in Nango, but it also works for Outlook if you pass the right scopes. Should probably find a better way to document this in the future :)

[Registering an OAuth app](https://learn.microsoft.com/en-us/azure/active-directory/develop/application-model) with Microsoft can be somewhat of a pain. Feel free to ping me on the Slack community if you have trouble with this and happy to help you out.

**Comment by mderazon** [comment]
@rguldener I am also looking for this, I've set up everything and authenticated but I am not sure how to use the Nango sdk to invoke the email api, couldn't find any documentation about it, the current documentation is thin on details:
https://docs.nango.dev/integrations/all/microsoft-teams
(Looking to send an email)

**Comment by bastienbeurier** [comment]
@mderazon you should join our [Slack community](nango.dev/slack) and post your question on #help-and-questions for a faster answer. 

You might want to use the [Proxy](https://docs.nango.dev/guides/proxy), which injects credentials into API requests.

**Comment by mderazon** [comment]
@bastienbeurier I will thanks. from the previous response I thought this is already supported, so I assumed there are ready templates I can use but I couldn't find anything so I guess I need to write the custom integration / action ?
The only thing I see in the dashboard is 2 sync functions:
![image](https://github.com/NangoHQ/nango/assets/717076/0aa54922-27aa-4b03-b8d8-09095b218cfe)
