### ISSUE TITLE
app template scaffold - examples would be great

### ISSUE THREAD

**Issue by hitesh97** [NangoHQ/nango#310]
Very excited to learn that OAuth for so many providers is available 👍  Great job!

Was wondering, if a few sample / scaffold applications using (NextJs, Create React App) would be good to show, how these api's
will work on SPAs as well as on NextJs server side (Secured route) etc.

**Comment by rguldener** [comment]
Hi @hitesh97,
sounds like a good idea. Do you have a particular use case in mind where you would like to use Nango? I am happy to see if I can help you navigate it with the current docs that we have :)

One side note: Nango provides a full solution for OAuth, so you do not need to add any routes to your backend to use it.

**Comment by hitesh97** [comment]
Hi @rguldener : Thanks for the prompt reply. I am thinking of starting up a pet project which is going to be a SaaS product (dashboard style project). 
When we think of a SaaS Product quite naturally, setting up Authentication on server and client is a basic necessity.

**Comment by rguldener** [comment]
Got it, thanks for the clarification hitesh!

Nango currently doesn't focus on OAuth for single sign on (or authentication of users of your app). Instead the focus is on obtaining API tokens to call external APIs.
For example, let's say you want to show a user's GitHub repositories on your dashboard. You could use Nango to get an OAuth token from GitHub for that user so you can call the GitHub API and fetch their repositories.
But to login to the dashboard itself, the user would (probably) use a login that is not powered by Nango.

For your use case of authenticating users for your app I would look at NextAuth for instance, which adds authentication to NextJS apps.

Does that make things a bit clearer?

**Comment by hitesh97** [comment]
Ok, I thought once we het oAith token from a given provider i.e github or gmail or Facebook etc.

We can get user info and a authentication token from those providers..  Once we have that the user is authenticated.. 

That one authentication token is enough for my app to keep it In the server side for making calls within APIs on server or frontend to keep sending the same token inside header..etc..


I did not mean to authenticate with one provider and then use same authentication token within other provider.

I may give it a try and see,if It can be done.

**Comment by rguldener** [comment]
I see, could work I think.
If you try it please let me know how it goes!

**Comment by rguldener** [comment]
Closing this one, @hitesh97 please feel free to reopen if needed!
