### ISSUE TITLE
Keycloak integration?

### ISSUE THREAD

**Issue by digoburigo** [NangoHQ/nango#311]
NextAuth has Keycloak integration
https://next-auth.js.org/providers/keycloak

Can your library support it or does not make senese?

**Comment by rguldener** [comment]
Thanks for the suggestion Digo!

We currently don't focus on the single sign on use case, so I am not sure an integration with keycloack would make sense now?
The main goals of Nango is to get OAuth tokens to call APIs to build integrations: For instance Slack bots, fetching contacts from HubSpot, reading the latest commits from private repos from GitHub etc.

You can also use Nango for single sign, but I am not aware of any project that is using it for this currently.

**Comment by rguldener** [comment]
Closing this one, @digoburigo please feel free to reopen if this becomes relevant for you.
