### ISSUE TITLE
Support custom subdomains for Nango Cloud

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#313]
Some OAuth providers, such as Google, show the redirect host prominently on the authorisation modal. See this example:
![image](https://user-images.githubusercontent.com/682011/217934627-989a0ad8-af9b-49a2-9cd9-d8bccf269699.png)

This can look scary or unprofessional.

It would be good if Nango Cloud users could setup a CNAME of eg `oauth.mycooldomain.com` that points to their Nango Cloud instance. The redirect then becomes `oauth.mycooldomain.com/oauth/callback` and Google shows `oauth.mycooldomain.com` as the redirect host.

**Comment by juancampa** [comment]
Looking forward to this!
