### ISSUE TITLE
Properly escape Connection ID in Frontend SDK

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#315]
If the connection-id contains a \, the redirect page never loads. The connection seems to have been created correctly AFAICT

<img width="985" alt="Screen Shot 2023-02-10 at 11 16 27 AM" src="https://user-images.githubusercontent.com/2560456/218143621-3c667315-bd26-43b9-902e-b7c0bfb1d8f4.png">

**Comment by Pranav2612000** [comment]
I'll like to work on this issue.

**Comment by bastienbeurier** [comment]
Thank you @Pranav2612000 !

**Comment by Pranav2612000** [comment]
@bastienbeurier I wasn't able to reproduce this issue ( Screenshot attached )
Do you have steps to reproduce this issue? Is it possible that it only occurs for a particular provider?

![image](https://user-images.githubusercontent.com/20909078/219872945-fd1512fa-0931-4ee4-9099-c397b98938fd.png)

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
