### ISSUE TITLE
Support API Key authentication

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#322]
We currently only support OAuth authentication. API Key is simpler and still used by less-mature APIs. 

#345 suggests interesting solutions for this.

[Spec](https://www.notion.so/nangohq/July-2023-API-Keys-8188de4bed064a0589a8c0976ff12172?pvs=4)

**Comment by bastienbeurier** [comment]
@t1mmen  @mmollick @davecyen @HarrisonJackson @Khaalidsub @0xRaduan would you mind sharing which API using keys you are interested in please? I'd like to inspect their docs to make sure we support them.

**Comment by Khaalidsub** [comment]
> @t1mmen @mmollick @davecyen @HarrisonJackson @Khaalidsub @0xRaduan would you mind sharing which API using keys you are interested in please? I'd like to inspect their docs to make sure we support them.

I know it is late, but  other than contentstack which supports proper oauth2 we use:
[datocms](https://www.datocms.com/)
[hygraph](https://hygraph.com/)
[contentful](https://www.contentful.com/developers/docs/)
