### ISSUE TITLE
Store scopes per Connections + enforce re-auth if missing scopes

### ISSUE THREAD

**Issue by matt-aitken** [NangoHQ/nango#326]
OAuth connections come with scopes and it's useful to know what they are so you can then request more when needed, or check that a particular connection has the required scopes.

Proposal
- Add a column to the connections table where the scopes are stored as an array of strings
- Add a new endpoint to the API to retrieve them, or just add the scopes as an additional object when getting the token

A specific function to do this:
`const accessToken = await nango.getScopes('<CONFIG-KEY>', '<CONNECTION-ID>');`

A very useful function so multiple API calls aren't requred
`const connection = await nango.getConnection('<CONFIG-KEY>', '<CONNECTION-ID>');`

// the returned object would look something like this:
```ts
{
  token: {
    type: "oauth2",
    token: "xo………………"
  },
  scopes: ["chat:write"],
  provider: "slack"
}
```

**Comment by bastienbeurier** [comment]
Adding to this, a user suggested: 

> also, in the our own implementation for integrations, I was building hash from scopes and storing for each customer installation, in that way I could compare scopes between customer and our implementation, and if the hashes were different, we were enforcing integration reinstallation in our system, do you plan to introduce similar feature? or did you think about this?

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
