### ISSUE TITLE
Quickbooks/Intuit: Store realmId from callback

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#328]
To call the quickbooks API developers have to pass in a realmId (seems to be a quickbooks account/company ID).
To get this realmId quickbooks returns it as [part of the OAuth callback](https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0#authorization-code).
Currently we don't store this, but we probably should store it along with the connection so developers can retrieve it together with the access token/credentials data.

To consider as we implement this:
* Salesforce (and other companies, such as Shopify and Zendesk) have APIs where the URL depends on the customer's instance. In the case of Salesforce the `instance_url` is returned together with the token response. It might make sense to consider if we can store this information in the same place as the realmId (aka "additional data about the connection")
* We might want to have a generic way to capture data passed in from callback parameters or from the token response

**Comment by rguldener** [comment]
Looks like braintree does something very similar with `merchantId`: https://developer.paypal.com/braintree/docs/guides/extend/oauth/access-tokens/node#values-returned-in-the-redirect-uri

**Comment by bastienbeurier** [comment]
Resolved by https://github.com/NangoHQ/nango/commit/f1fee62aa491a6e70360282be64f339f5fb7267c
