### ISSUE TITLE
Quick test support for remote servers

### ISSUE THREAD

**Issue by fishandsheep** [NangoHQ/nango#330]
I have almost no base environment installed on my local computer, but I wanted to have a quick experience with this project via a remote server.
Finally ,i replacing `localhost` with the public IP in the following files, and local browser test is fine.

_packages/auth/lib/utils/utils.ts_
```
...
export function getBaseUrl() {
    return process.env['NANGO_SERVER_URL'] || 'http://localhost:3003';
}
...
```

_packages/frontend/bin/sample.html_
```
...
  var nango = new Nango({ host: 'http://localhost:3003' });
...
```

I tried to change the `NANGO_SERVER_URL=http://localhost:3003` in the _.env_ file, but it didn't work.

It would be nice to support remote server for quick testing.
THANKS.

**Comment by rguldener** [comment]
Hi @fishandsheep 

We have docs on how to quickly deploy Nango to a remote server here: https://docs.nango.dev/category/deploy-nango-sync-open-source
The Render deployment option even works with a single click.

Is there anything specific in there that was not clear for you?

**Comment by rguldener** [comment]
Closing this one @fishandsheep, please feel free to reopen if you need more help here!
