### ISSUE TITLE
Feature request: Other means of creating configurations outside of the cli

### ISSUE THREAD

**Issue by beacoding** [NangoHQ/nango#334]
Right now, we're required to run `npx nango config:create` etc. into a box, which is useful if you have access to it.

It would be nice to have a wrapper to call it within code as well. 

For now, I just dug into your CLI code and called the endpoint `npx nango config:create` uses.

**Comment by bastienbeurier** [comment]
This has been done since. Here's the reference: https://docs.nango.dev/api-reference/overview
