### ISSUE TITLE
Make frontend SDK compatible with server side rendering

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#335]
A user has reported that they had issues with the frontend SDK and server side rendering (SSR) in NextJS: The window object was not set at the time of rendering and our SDK crashed because of that.

For Next SSR it works fine if we just add a check first if window if set, and if not do nothing:
```js
if (typeof window === 'undefined') {
// No op
} else {
// Do our business
}
```

I am not a frontend/SSR expert so not sure if this solution will work for all frameworks/cases.
Help from a frontend/SSR expert would be appreciated!

**Comment by t1mmen** [comment]
FWIW, I ran into this with NextJS+SSR. Workaround sample below using `@nangohq/frontend@0.8.0`:

```tsx
export default function IntegrationsPage(props: Props) {
  const nangoRef = React.useRef<Nango | null>(null);

  useEffect(() => {
    nangoRef.current = new Nango({
      publicKey: process.env.NEXT_PUBLIC_NANGO_PUBLIC_KEY,
    });
  }, []);

  const handleAuth = async (configId, connectionId) => {
    if (nangoRef.current === null) return;
    nangoRef.current.auth(configId, configId);
  };

  return (
    <>
      <button onClick={() => handleAuth('zoom', props.user.id)}>
        Connect Zoom
      </button>
    </>
  );
}
```

**Comment by Pranav2612000** [comment]
I think the solution suggested by @rguldener should work. This is also the solution suggested on the official vercel forum https://github.com/vercel/next.js/issues/2473
Using dynamic imports can also be a temporary solution but we'll need to test it out first.

If it's fine, I can work on these tasks. While I add the `isBrowser` check I'll also try reproducing the issue and checking if dynamic import fixes it.
