### ISSUE TITLE
Deleting a provider config does not delete the associated connections

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#340]
Not a bug per se but probably unexpected behaviour:
When you delete a provider config with the CLI `npx nango config:delete` it deletes the provider config. But the connections that are associated with this provider config stay around. It looks like this is not an issue today, but it might not be what users expect.

There is also no warning/confirmation before the deletion. We could add a warning and maybe an option for users to delete all connections along with the config.

**Comment by bastienbeurier** [comment]
Resolved by https://github.com/NangoHQ/nango/pull/367
