### ISSUE TITLE
Add support for nango.setToken

### ISSUE THREAD

**Issue by HarrisonJackson** [NangoHQ/nango#345]
One of the best things Nango does for me is securely handling user secrets. It would be great if there was a way to push more user secrets into nango for retrieval later.

This would be great and matches the current access patterns
```
await nango.setToken('contentful', '<user-id>', 'non-expiring-token');
```

Also opens up more general secret storage where instead of a service the first param is just a namespace for storing user secret data
```
await nango.setSecret('namespace', '<user-id>', JSON.stringify({key1: value1, key2: value2}));
```

And could also store account level secrets.
```
await nango.setSecret('secret-key', 'secret-value');

// under the hood this could just call setSecret with namespace: account
await nango.setSecret('account', 'secret-key',  'secret-value')
```

This suggestion came from the current limitation around implicit grant oauth flow here https://github.com/NangoHQ/nango/issues/343

**Comment by bastienbeurier** [comment]
This is a great suggestion, like a generalisation of #322. Also not to hard to add. I'll add it to the roadmap. Lmk if it becomes pressing and we can accelerate.

**Comment by Khaalidsub** [comment]
We would like to have this feature as well, since some of our providers do not technically conform oauth1/oauth2, however we would like to access all the tokens from the nango sdk.

Currently, similar to how we get the token `nango.getToken(provider,connectionId)`, we store the external token providerd

**Comment by 0xRaduan** [comment]
+1 to this feature as well.

**Comment by bastienbeurier** [comment]
Closing as duplicate with #322 but will link this issue there to reference the suggested solution.
