### ISSUE TITLE
Handle case where access token doesn't expire + refresh token is present

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#348]
<img width="1115" alt="Screenshot 2023-02-23 at 09 23 48" src="https://user-images.githubusercontent.com/2560456/220855382-3737e31a-bcf6-4e5a-b49b-87b1b41ba660.png">

We should disable that check, maybe just for Stripe.

**Comment by HarrisonJackson** [comment]
https://github.com/NangoHQ/nango/pull/347

Hey Bastien! Happy to add a check for Stripe instead of just removing the error handling. PR open that removes the error handling so let me know on there if yall have a preference.

**Comment by bastienbeurier** [comment]
Hey! Sorry I created this before seeing your PR. I think it's okay to not make it Stripe-specific just yet. Commented directly on the PR.

**Comment by bastienbeurier** [comment]
Resolved by #347
