### ISSUE TITLE
Implement a Youtube integration

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#354]

**Comment by rguldener** [comment]
Needs a check if this is already covered by `google` OAuth or a separate OAuth flow

**Comment by HarrisonJackson** [comment]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/1638561/221446472-b5555e9c-1683-4373-b8a4-07313e93bab7.png">

It is working for our integration.

**Comment by rguldener** [comment]
Indeed.

I added a page for YouTube to the Nango providers list with details on how to set it up for each of the three APIs it offers: https://docs.nango.dev/providers/youtube
