### ISSUE TITLE
Support long-lived access tokens & refresh tokens for Instagram Basic Display API

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#357]
The Instagram Basic Display API has a very non-standard OAuth flow.
Our current implementation works to authorize and get a first, short-lived access token.

For permanent access additional steps are required:
1. With the short-lived access token we need to make another access token request to a different endpoint to get a long-lived access token: https://developers.facebook.com/docs/instagram-basic-display-api/reference/access_token
2. To refresh that access token the API uses a non-standard request format, restrictions and endpoint: https://developers.facebook.com/docs/instagram-basic-display-api/reference/refresh_access_token

Currently Nango does not support a flow like this.

If you need this functionality please comment here so we know how to prioritize this issue.

**Comment by harrisyn** [comment]
Definitely thought this was already embedded.
instagram is primarily my use case

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
