### ISSUE TITLE
Print Nango server version in startup message

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#374]
We should print the version of the Nango server in the "server is up" success message. This will help a lot with debugging server issues, currently it is impossible to tell from logs which version of the Nango server is running.

There also does not seem to be any easy way to tell from the docker images what the version is, as we always fetch the "latest" tag (but that can be outdated if the user doesn't explicitly re-request the image).

**Comment by uncle-tee** [comment]
can we use the version in the package json here, or what do you think?

**Comment by bastienbeurier** [comment]
Resolved by https://github.com/NangoHQ/nango/pull/380
