### ISSUE TITLE
Improve Connection configuration on the Connection creation page

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#384]
Currently, if you use an integration requiring some extra configuration, you pass in this configuration in JSON format on the webapp (in the "Connection Configuration Parameters" field).

<img width="1507" alt="Screenshot 2023-03-21 at 09 11 51" src="https://user-images.githubusercontent.com/2560456/226670656-3a19307c-2170-44e2-9f78-1c4d8c2671f3.png">

We should handle this more gracefully with generated fields based on the specific integration. All of this should be reflected in the generated frontend code snippet.

**Comment by uncle-tee** [comment]
Please can you share more details on this please?

**Comment by bastienbeurier** [comment]
Resolved by https://github.com/NangoHQ/nango/commit/ed46b1c55b2c4bac21823cb499ad00d8803b0c9a
