### ISSUE TITLE
Missing js.map in Frontend SDK

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#385]
Using the frontend SDK in a React app shows the following error:
<img width="675" alt="Screenshot 2023-03-21 at 06 36 30" src="https://user-images.githubusercontent.com/2560456/226670917-d4d501de-9542-4dfa-ba5a-01c7711c4c64.png">

**Comment by bastienbeurier** [comment]
Additional info: https://github.com/NangoHQ/nango/pull/542#issuecomment-1512659778

**Comment by bastienbeurier** [comment]
Had to reopen because of a bug the fix was creating -> https://github.com/NangoHQ/nango/pull/614

The outside fix is tracked here https://github.com/facebook/create-react-app/pull/11752

**Comment by gorets** [comment]
Your `dist/index.js` has relation `# sourceMappingURL=index.js.map` but file `index.js.map` doesn't included in the npm package.

I think it would be correct to add this file to the package, but whether it will be used or not in the final application bundle should be decided by the author of the application, and not the author of a specific module. 

P.S. see bootstrap as example

![image](https://github.com/NangoHQ/nango/assets/419682/00e54f41-f959-40c1-b18a-854deb827da2)

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
