### ISSUE TITLE
Issues with token refreshing (ignored params, token params overrides refresh grant type)

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#392]
Currently the params from `token_params` are also applied for refresh token calls. If there is a grant_type=authorization_code in there it will also get passed for refresh calls and override the refresh token grant type. This leads to bugs, as [with contentstack recently.](https://github.com/NangoHQ/nango/blob/cbd151c38e2fe7394912f8c14ae6a1fb6ce7f5d0/packages/server/providers.yaml#L66)
Fix for now is to make sure grant type is not set for token_params but not sure these should be applied at all?

A separate but closely related issue: It seems our token refresh code ignores the `refresh_url` and `refresh_parameters` completely and always applies the token URL & params?
See implementation here: https://github.com/NangoHQ/nango/blob/master/packages/server/lib/clients/oauth2.client.ts#L50

**Comment by bastienbeurier** [comment]
Resolved by https://github.com/NangoHQ/nango/commit/46b4677f42c57f1161e138238413554414066859
