### ISSUE TITLE
BambooHR

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#394]
I received a request to day for BambooHR support.
It looks like their API supports OAuth 2 (they call it the openID flow): https://documentation.bamboohr.com/page/single-sign-on-sso-with-openid-connect

To get a client id and secret for testing we need to apply for a partner account here: https://partners.bamboohr.com/apps-marketplace-program/
I submitted an application/registration and will update this ticket when I hear back.

**Comment by rguldener** [comment]
I got access to the dev portal (@bastienbeurier has access as well).
Happy to provide a client id & secret to the person implementing this issue.

**Comment by chandu-ex** [comment]
@rguldener I would like to work on this (if this has not been picked up already)

**Comment by Chandu** [comment]
@rguldener I would like to work on this (if it's still open)

**Comment by bastienbeurier** [comment]
You are welsome to work on this integration @Chandu !

**Comment by Chandu** [comment]
> You are welsome to work on this integration @Chandu !

@bastienbeurier @rguldener Could you share the client_id/secret, company name please?

**Comment by bastienbeurier** [comment]
Circling back privately on the Slack community

**Comment by bastienbeurier** [comment]
Resolved by https://github.com/NangoHQ/nango/pull/486
