### ISSUE TITLE
Typeform

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#414]

**Comment by Khaalidsub** [comment]
While trying to test the typeform integration. Everything succeeded(oauth callback and a sucess notification from nango dashboard) , nango is not storing the new connection and the logs are saying there is an unexpected error :

![image](https://user-images.githubusercontent.com/48145776/228669515-421fedbd-e1c2-4006-8d40-57f3ea15ec2a.png)

**Comment by bastienbeurier** [comment]
Hi Khalid! 

This usually happens when the external API returns an error. E.g. the provider credentials are wrong (app ID, secret, scopes), access has been revoked, etc. We plan to make this more self-explanatory in the near future.

I will try to reproduce on my end in case the problem is on Nango's side. I'll report back soon!
