### ISSUE TITLE
Connection ID with backslash prevents deletion

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#423]
Reported by Juan on the Slack community, coud reproduced by creating a Connection with a `\` character.

**Comment by motnyk** [comment]
Hi @bastienbeurier, is this still relevant?

I was going to try and fix this but I wasn't able to reproduce this or find Juan's report on community Slack. The only seemingly related thread I found is https://nango-community.slack.com/archives/C04ABR352H0/p1680077423232399 but the issue there is related to forward slash and is already fixed.

**Comment by bastienbeurier** [comment]
Thanks a lot for checking this one @motnyk. Let's close it for now and reopen if needed!
