### ISSUE TITLE
Synthesio

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#453]

**Comment by uncle-tee** [comment]
Please can you provide a link to their developer platform for this?

**Comment by rguldener** [comment]
It looks like the Synthesio API docs are here: https://support.synthesio.com/support/solutions/6000132326
But most of them require a login to view and it seem they use the "password" grant type of OAuth 2.

I think we can keep this on blocked until we have a customer who can help us access the API docs & give test credentials.

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
