### ISSUE TITLE
Nango provided client id & secret for testing of new integrations

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#469]
Currently users always need to supply their own client id & secret to add an integration to Nango. This means registering with the API provider to obtain them, which can be cumbersome and unintuitive.

To help people get started faster with a new API we could let users "rent" a client id & secret from us:
When you add an integration for a provider we support, you could choose whether you want to use Nango's test client id & secret or supply your own.

This would make testing new APIs faster because you don't have to worry about registering your own client id & secret until you want to move into production.

If you think this would be helpful for you to test new APIs please leave a reaction or comment here.

**Comment by rguldener** [comment]
Thanks for chiming in @uncle-tee and I agree that there is potential for abuse here. To safeguard this we could implement restrictions such as:
- Nango provided client ids & secrets can only be used in the dev environment (see also #470 )
- A limit of 5 connections per Nango provided client id & secret per Nango account
- Verify email address (+ possibly phone number if needed) before users can use Nango provided client ids & secrets
- Implement this in such a way that the Nango provided client id & secret is not visible to the user (so they cannot use them outside of Nango's environment)

As mentioned in the initial comment, I see the value here in getting started fast. For production deployment I would still expect people to get their own client id & secret.

**Comment by bastienbeurier** [comment]
Less relevant now that we focus on syncing data. Let's re-open if needed.
