### ISSUE TITLE
Support multiple development environments

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#470]
Currently all integrations and connections in Nango are in a single namespace.
To improve the DX, it would be great to separate staging & test data from production data.

For this each integration and connection could be associated with an environment. Every account gets 2 of these: Dev & prod.
To identify the environment we could issue different public & secret keys for them as well.
A switcher in the UI could let a user jump between Dev & Prod environments within an account.

**Comment by bastienbeurier** [comment]
Duplicate with #734
