### ISSUE TITLE
Generated frontend code snippet shows localhost URL when self-hosting on remote server

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#475]
![CleanShot 2023-04-06 at 15 30 32@2x](https://user-images.githubusercontent.com/2560456/230570688-1d099e50-1ece-44de-ab61-6486796650fd.png)

> Hey guys! When self-hosting Nango with render and testing out an OAuth connection, it automatically tries to connect to localhost:3003. However the actual host should be something like https://nango-server-abcd.onrender.com/

In this case, it should show the URL of the actual server being used (original [thread](https://nango-community.slack.com/archives/C04ABR352H0/p1680820286487569)).

**Comment by jasonwcfan** [comment]
Thanks for opening @bastienbeurier. Another part of this issue is that the button "Start OAuth Flow" also assumes localhost as where nango is being run from so it doesn't work when deployed as a container.

**Comment by bastienbeurier** [comment]
Reported again in this [thread](https://nango-community.slack.com/archives/C04ABR352H0/p1683100747842739?thread_ts=1682401933.017369&cid=C04ABR352H0) on the community.

But turned out Nginx needed to have WebSocket enabled.
