### ISSUE TITLE
Returning Expired Tokens for Providers without Refresh Tokens Causes Unauthorized Errors

### ISSUE THREAD

**Issue by uncle-tee** [NangoHQ/nango#482]
**Description**

There are certain providers who lack refresh tokens. In order to determine whether we should refresh, we currently verify the credentials for the presence of refresh tokens. However, if there are no refresh tokens, we return the credentials.

The problem is that we continue to return the expired token to clients. Consequently, when clients attempt to use the token with the provider, it fails with an "unauthorized" error. To prevent this, we need to raise an error in such cases, so that clients are notified and can initiate the Authorization process anew.

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
