### ISSUE TITLE
Add option to rotate secret and public keys for Nango account users

### ISSUE THREAD

**Issue by uncle-tee** [NangoHQ/nango#488]
**Description**

We should create a possibility to rotate the secret key and public key, for the Nango account users, in case the secret key has been compromised.

**Comment by aady07** [comment]
Thank you for the opportunity to contribute! I'm interested in working on this issue and have already started working on the server-side code for key generation. Could you please provide more details on what else needs to be implemented for the key rotation feature? For example, should there be a specific API endpoint for users to rotate their keys? Are there any security considerations that need to be taken into account when implementing this feature? Any additional information would be helpful in completing this task

**Comment by aady07** [comment]
> Thank you for the opportunity to contribute! I'm interested in working on this issue and have already started working on the server-side code for key generation. Could you please provide more details on what else needs to be implemented for the key rotation feature? For example, should there be a specific API endpoint for users to rotate their keys? Are there any security considerations that need to be taken into account when implementing this feature? Any additional information would be helpful in completing this task
