### ISSUE TITLE
Ebay

### ISSUE THREAD

**Issue by uncle-tee** [NangoHQ/nango#494]

**Comment by bastienbeurier** [comment]
Thanks for taking a stab at this one @saru2020. Maybe the 1st answer of this thread could help? https://stackoverflow.com/questions/45088006/nodejs-error-self-signed-certificate-in-certificate-chain

**Comment by saru2020** [comment]
I got the keyset for prod env but even the authorization isn't working and throws 500 unavailable error: `{"error_id":"temporarily_unavailable","error_description":"The authorization server is currently unable to handle the request.","http_status_code":500}`

have posted the [same issue in eBay community portal](https://community.ebay.com/t5/eBay-APIs-Talk-to-your-fellow/OAuth-prod-env-always-return-500-error/m-p/33685871#M137)
