### ISSUE TITLE
ServiceNow

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#518]
According to their docs the REST API supports OAuth 2: https://developer.servicenow.com/dev.do#!/reference/api/tokyo/rest/
I couldn't find details yet though how to set that up. It is also unclear to me if there is a multi tenant cloud or if every customer would be a single tenant anyway (in which case API key might actually be easier).

**Comment by bastienbeurier** [comment]
Closing issues related to new API support that was not specifically requested by a customer.
