### ISSUE TITLE
Log query params of request during redirect

### ISSUE THREAD

**Issue by uncle-tee** [NangoHQ/nango#527]
While authorizing, several providers might include an error in the query parameters during redirection, which is useful for both the user and logging purposes. Therefore, it is recommended to log the request query after the callback.

To reproduce the error, 
- you can create an integration with Square-Up and add a random scope, 
- then initiate the authorization. 
- The authorization will fail with reasons listed in the query parameters during the redirection process.

**Comment by bastienbeurier** [comment]
Has been done as part of the Activity tab
