### ISSUE TITLE
Integration Request: Slack

### ISSUE THREAD

**Issue by 0xRaduan** [NangoHQ/nango#537]
Seems like they are also having OAuth 2.0: https://api.slack.com/legacy/oauth

**Comment by rguldener** [comment]
We already support [Slack's OAuth 2.0 V2 flow](https://api.slack.com/authentication/oauth-v2), but I understand this is a request for their legacy flow?

Can you briefly outline which use-cases are only covered by the legacy flow?

**Comment by 0xRaduan** [comment]
Indeed, sorry – seems like I missed this – @rguldener. Gonna close out the issue in this case.
