### ISSUE TITLE
Provide an OpenAPI spec for Nango backend APIs

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#543]
Some users have existing infrastructure for handling APIs & prefer to use the REST API with an OpenAPI spec.
We currently don't provide an open API spec for the backend/connections API, which means more manual work for them.

**Comment by Adedunmol** [comment]
Hi @rguldener, I’d like to be assigned this. Any resource on how to set up the project locally?

**Comment by bastienbeurier** [comment]
Done with https://docs.nango.dev/api-reference/overview
