### ISSUE TITLE
Force refresh token on the web UI

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#544]
This [PR](https://github.com/NangoHQ/nango/pull/465) added an endpoint to force a token to refresh, which makes testing the refresh functionality easier. 

Adding it to the web UI would make this feature more accessible and would allow us to capture refresh errors more easily.

**Comment by Chakravarthy7102** [comment]
> This [PR](https://github.com/NangoHQ/nango/pull/465) added an endpoint to force a token to refresh, which makes testing the refresh functionality easier.
> 
> Adding it to the web UI would make this feature more accessible and would allow us to capture refresh errors more easily.

Hey @bastienbeurier can you please guide me where to add this piece in the UI?

**Comment by bastienbeurier** [comment]
Here's a proposed UI: 

<img width="1512" alt="Screenshot 2023-04-24 at 10 08 21" src="https://user-images.githubusercontent.com/2560456/233937450-f958b1db-5d62-400a-906f-ccc33acb8edb.png">

The refresh logo can be found on https://heroicons.com/. 

In case of success, we could show the same success/error toasts that we use in `IntegrationCreate.tsx` from `react-toastify`. 

Let me know if anything is missing or you have questions!
