### ISSUE TITLE
Use text edit with tags for scopes

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#546]
Currently scopes need to be comma separated in the Nango web UI. We should use tags instead, which would make for a cleaner UI and spares developers from thinking about the separator type.

**Comment by Chakravarthy7102** [comment]
> Currently scopes need to be comma separated in the Nango web UI. We should use tags instead, which would make for a cleaner UI and spares developers from thinking about the separator type.

Also If we were be able to auto complete the scope values while typing would be nicee.

**Comment by bastienbeurier** [comment]
That would be ideal, but we would need to maintain a list of scopes for each integration, which is hardly realistic at this point :/
