### ISSUE TITLE
Proxy interface proposal

### ISSUE THREAD

**Issue by khaliqgant** [NangoHQ/nango#552]
The goal is to go beyond handling the OAuth and provide a proxy to make the actual API request. [Pizzly](https://github.com/NangoHQ/nango/blob/2c2e999d505058c1114611bc26f9c9a4243ee435/docs/proxy.md) had a proxy for making requests and merge also has a [passthrough API](https://docs.merge.dev/supplemental-data/passthrough/).

The deliverable on this issue is to come up with an easy to use and understand interface to make API calls for both the Node.js SDK and the REST API.

**Comment by khaliqgant** [comment]
# Proposal 1.0

## What Is It?
Same familiar simple interface with a lot of functionality baked in:
1. Handles authentication
2. Handles retries
3. Takes care of logging
4. Handles rate limits
5. Scales as you scale

```
const repsonse = await nango.proxy({
    endpoint: 'user',
    providerConfigKey: 'XXX',
    connectionId: 'XXX'
});

## SDK Usage
1. Install and set up the SDK as described in [the sdk docs](/reference/node-sdk)
2. Use the proxy to both authenticate and make an API call in one simple step
```js
# note these params closely follows how axios structures their API
const response = await nango.proxy({
    method: '<HTTP-METHOD>',    // GET is the default if not provided
    endpoint: '<API-ENDPOINT>', // exclude the base API URL
    providerConfigKey: '<PROVIDER-CONFIG-KEY>',
    connectionId: '<CONNECTION-ID>',

    // optional parameters
    headers: '<HEADERS>',
    params: '<PARAMS>',   // URL parameters to be sent with the request. Must be a plain object or a URLSearchParams object
    paramsSerializer: {
        encode?: (param: string): string => { /* Do custom ops here and return transformed string */ }, // custom encoder function; sends Key/Values in an iterative fashion
        serialize?: (params: Record<string, any>, options?: ParamsSerializerOptions ), // mimic pre 1.x behavior and send entire params object to a custom serializer func. Allows consumer to control how params are serialized.
        indexes: false // array indexes format (null - no brackets, false (default) - empty brackets, true - brackets with indexes)
      },
    data: {
        param: 'VALUE'
    }
});
```

### Example
```js
const insertCalendarListResponse = await nango.proxy({
    method: 'POST',
    endpoint: 'users/me/calendarList',
    providerConfigKey: '<PROVIDER-CONFIG-KEY>',
    connectionId: '<CONNECTION-ID>',
    data: {
        id: 1,
        colorId: 'blue',
        selected: true
    }
});
```

## REST API Usage


* Nango Cloud
```bash
curl 'https://api.nango.dev/proxy/<CONNECTION-ID>?provider_config_key=<CONFIG-KEY>&method=<METHOD>&endpoint=<API-ENDPOINT>'\
-H 'Authorization: Bearer <SECRET-KEY>'
```
* Localhost
```bash
curl 'http://localhost:3003/proxy/<CONNECTION-ID>?provider_config_key=<CONFIG-KEY>&method=<METHOD>&endpoint=<API-ENDPOINT>'
```
* Self hosted
```bash
curl '<NANGO-HOST-AND-PORT>/proxy/<CONNECTION-ID>?provider_config_key=<CONFIG-KEY>&method=<METHOD>&endpoint=<API-ENDPOINT>'
```

**Comment by HarrisonJackson** [comment]
This would have been great to have when we started building out our backend integrations. I like that it would reduce all our dependencies on troublesome clients/sdks down to just nango.

Is this intended to replace Axios or to replace the provider's sdks/clients?

Replacing axios does basically nothing for us. It saves us the call to nango to get the token but then the example code for `nango.proxy` looks basically the same as using axios.

Replacing the clients would be nice for the ones that have a lot of dependencies or are poorly written. But the good clients with support for typescript are great to use and this would be a poor replacement without the typescript support.

What does the documentation for this look like in nango? Are you going to have documentation for every api and all the supported endpoints?

Pros:

* eliminate external dependencies
* more consistent interface for talking to all the providers
* single source of documentation for all the apis
* logging/monitoring/alerting are nice to haves

Cons

* good clients with good typescript support will be really hard to switch away from
* without full coverage of a provider's api we'd have an awkward codebase for each integration
* larger burden on contributors, potentially slower to ship new integrations

I think my biggest reservation is the typescript support. Most nodejs clients have typescript support and when it works it is so helpful. Stripe is a good example. They have an enormous API and each object has tons of properties. Without typescript and vscode typescript autocomplete working with their api would be really annoying.

100% there are some providers we would switch to `nango.proxy` - all of the google apis, definitely if there was full coverage. Others, such as Stripe, I don't see the value add.

Hope that makes sense!

**Comment by khaliqgant** [comment]
Initial version has been merged with #562

**Comment by wub** [comment]
Hey @khaliqgant, regarding this:

> In some responses rate limits are included so we will look for and respect those by throttling requests accordingly. If not present requests will use a sane default to throttle requests.

In the event of a rate limit event occurring, how does the proxy respond? For example, if the Meta API responds and says "you're rate limited for 900 seconds":

* Does the request block for 900 seconds?
* Does the request throw a rate limit-specific exception that needs to be handled by the caller?
* Something else?

Some APIs also provide "current usage" headers on responses - for example, `X-CPU-Credit-Usage: 86%`.  If the value hits 100, the API locks us out for a longer period of time; we want to slow down *before* hitting the "hard" rate limit (say, at 90% usage). Will it be possible to hook into the rate limiter system so we can check headers and force a rate limit event on ourselves?

Cheers!

**Comment by bastienbeurier** [comment]
After answering on the [community](https://nango-community.slack.com/archives/C03QBHSMPUM/p1681914763504169), adding my answer here too for visibility. 


Thanks for your input   @wub 

> Does the request block for 900 seconds?
Indeed, the proxy is synchronous at the moment, so it waits for the retries to execute (cf. [docs](https://docs.nango.dev/reference/proxy#retries)). Similarly to a regular HTTP library like axios.

> Does the request throw a rate limit-specific exception that needs to be handled by the caller?
It transparently returns the error from the external API. So if the external API returns a rate-limit error, that's what you will receive from the proxy (once all the retries are exhausted).

> if it blocks the request for a few seconds (say up to something like 10 seconds), I would strongly prefer waiting for the request than to have an errored request.
You can configure this with the number of retries (cf. docs). We will expose more fine-grained retry parameters as we go.
In general, if you are using the proxy for synchronous processing (e.g. your main server), I would only do 1-3 retries, to avoid blocking the execution for too long. But if you are running background jobs that can be long-lived (e.g. with Temporal), then it's fine to have more retries & longer delays between retries.

@wub we are planning to leverage rate-limit headers in the try strategies, but that again would only work if you execute the proxy in a long-lived background job.

@wub @AnandChowdhary is this sub-optimal for you? Do you think of any way we can make it better?

**Comment by AnandChowdhary** [comment]
No, this seems great! We are doing something very similar internally already (e.g., retries etc.) so I'm glad I'll be able to replace that with this! I would highly recommend a timeout option, I couldn't find that anyway, e.g., I want to have a strict timeout of 30 seconds on request so it just throws after that period if there's still no response, which is useful to prevent blocking.
