### ISSUE TITLE
The provided public key is not a UUID v4

### ISSUE THREAD

**Issue by enrico21stjuly** [NangoHQ/nango#577]
The key is what has been given in the dashboard

<img width="494" alt="image" src="https://user-images.githubusercontent.com/77277496/234156073-0a3976b9-a49e-427e-bb4e-62185ef9f0d1.png">

It seems that I cannot regenerate it, so I am stuck.

**Comment by bastienbeurier** [comment]
@enrico21stjuly is this still happening?

**Comment by enrico21stjuly** [comment]
> @enrico21stjuly is this still happening?

Hey @bastienbeurier , I actually opted for a different implementation as I was having too many issues on both frontend and backend.

However, I should add that I also checked the UUID validity of the provided public key with another tool and it was not valid.
