### ISSUE TITLE
Allow programmatically adding new integrations

### ISSUE THREAD

**Issue by 0xRaduan** [NangoHQ/nango#586]
Saw that there is no API for adding integrations, only https://docs.nango.dev/reference/connections-api

I think it would be beneficial to add that, because for example, if I have many integrations(and need to setup nango quickly for some reason – maybe integration testing or something similar), that would be really beneficial to speed up our workflows.

**Comment by rguldener** [comment]
Thanks for raising this @0xRaduan !
Actually an API already exists for this today, but you are right that is not documented yet. We have an open issue for this here: #548 
It also has the details on where to find the API in the code so you can already use it if needed.

Does that help? Or did you have something else in mind?

**Comment by 0xRaduan** [comment]
Yep, feel free to close this one as duplicate.
