### ISSUE TITLE
Support hmac feature on Cloud

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#593]
This has been introduced for OSS by #591. We should have the same available on Cloud.

**Comment by Chakravarthy7102** [comment]
@bastienbeurier I would like take this one on, but I'm not sure how to go about on this, more context would be great :)

**Comment by Chakravarthy7102** [comment]
> Hi @Chakravarthy7102 and thank you for proposing to take on this.
> 
> We are planning some big chances on the platform in the coming weeks. If you don't mind, I would wait until we have a bit more clarity before making that change, to make sure it fits!

sure!
