### ISSUE TITLE
Properly format log messages in combined.log and error.log

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#60]
Currently we do not format log messages before they get written, so they come out as JSON and lack some basic information such as datetimestamps.

We should properly format the messages for combined.log and error.log, possibly with different formats for different loggers. There are some examples of this in the old Nango here (there were different formats for server messages, OAuth messages & log messages from an action run): https://github.com/NangoHQ/nango/blob/7dfa5ffb02b98af13bc608a04621daf73f6bb13e/packages/server/lib/logging.ts

The examples above are probably easier than [Winston's documentation](https://github.com/winstonjs/winston#formats), which is a bit lacking on this topic.

**Comment by bastienbeurier** [comment]
Resolved by https://github.com/NangoHQ/nango/pull/65
