### ISSUE TITLE
Retrieving Connections tied to a specific connection_id

### ISSUE THREAD

**Issue by clarkeRS** [NangoHQ/nango#601]
An interesting use case is when a user has multiple OAuth connections on a single platform. So to standardize and make quick retrieval of the auth token, using the user_id as the connection_id makes it much simpler. But when checking to see what the user has connected to we have to pull all connections and filter by their user_id once we retrieve it.

**Comment by bastienbeurier** [comment]
Fyi, this will be part of Monday's release!
