### ISSUE TITLE
Use a link, instead of the Frontend SDK, to trigger the OAuth flow 

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#603]
This was suggested on the community [here](https://nango-community.slack.com/archives/C04ABR352H0/p1682670631353629).

> Is there a way to add a link to an email for example for someone to connect their OAuth2 with Nango?
> So a button or something like that in an Email going directly to the authorization page without the need to have a specific > > page for this where to embed this authorization button and such.

**Comment by bramkn** [comment]
I see @uncle-tee Already did the work on this.
Was planning on spending some time the next couple of weeks to see if I could fix it. So I am very happy it was already done.
Is there any estimated time frame when this and the dependent PRs can be merged?
@bastienbeurier
