### ISSUE TITLE
Mixpanel

### ISSUE THREAD

**Issue by Cuteladyj** [NangoHQ/nango#608]
can someone add mixpanel API

**Comment by VatsalNagelia** [comment]
It seems to me OAuth2.0 is not enabled by Mixpanel, there are four methods of authentication and currently they use Basic Authentication. Reference [Here](https://developer.mixpanel.com/reference/authentication).
But also, I found this that user-specifically they use OAuth although (Reference [here](https://developer.mixpanel.com/docs/privacy-security#authentication)), I was having trouble understanding how to implement that in Nango as they have not provided any token url, instead token needs to be added manually in the URL. Could someone guide me if I am missing something.
