### ISSUE TITLE
Support Amplitude

### ISSUE THREAD

**Issue by Cuteladyj** [NangoHQ/nango#609]
please add it

**Comment by bastienbeurier** [comment]
Hi @Cuteladyj, thanks you for posting this! 

I'd be happy to chat about the urgency of the Amplitude/Mixpanel integrations on the [community](https://nango.dev/slack). Feel free to ping me there (my handle is @bastien). 

Also, if you want to accelerate the implementation, here's a [guide](https://docs.nango.dev/contribute-api) for contributing new APIs.

**Comment by VatsalNagelia** [comment]
I'm afraid amplitude does not support OAuth. Reference [Here](https://www.docs.developers.amplitude.com/partners/event-streaming-integration-guide/?h=oauth#limitations)
Moreover, I couldn't find much reference to OAuth in the documentation for amplitude.
![image](https://user-images.githubusercontent.com/52467754/235885240-7dd48454-3c70-4c93-8adf-7152f9fac393.png)

**Comment by bastienbeurier** [comment]
Thank you for investigating @VatsalNagelia. There's an issue to track API Key auth (#322). We should get to it fairly soon and unblock Amplitude.

**Comment by bastienbeurier** [comment]
For the [Export API](https://www.docs.developers.amplitude.com/analytics/apis/export-api/), Amplitude uses Basic Auth: 

> This API uses [basic authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization#basic_authentication), using the API key and secret key for your project. Pass base64-encoded credentials in the request header like {{api-key}}:{{secret-key}}. api-key replaces username, and secret-key replaces the password.
> 
> Your authorization header should look something like this:
> 
> --header 'Authorization: Basic YWhhbWwsdG9uQGFwaWdlZS5jb206bClwYXNzdzByZAo'

[Instructions](https://www.docs.developers.amplitude.com/analytics/find-api-credentials/) to find credentials.

**Comment by khaliqgant** [comment]
Done with #322
