### ISSUE TITLE
Expose logs from docker container in the Nango repo (when running with docker compose)

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#61]
Currently when Nango runs in the docker container the log files get written to a file that is in the docker container. This makes it hard for users to access these logs and debug issues.

When the docker containers are run with docker compose (and we thus know the user is running it from within the Nango repo) we should write these doc files to `logs/combined.log` and `logs/error.log` in the repository so the user can easily inspect them.

One solution for this could be to use bind volumes, which would easily allow us to bind the `logs` folder into a folder in the container. The old Nango has an example of this here: https://github.com/NangoHQ/nango/blob/7dfa5ffb02b98af13bc608a04621daf73f6bb13e/docker-compose.yaml
This will also help with production deployments as it gives users a way to specify where log files should get written.

**Comment by bastienbeurier** [comment]
Resolved by https://github.com/NangoHQ/nango/pull/65
