### ISSUE TITLE
Activity tab follow up

### ISSUE THREAD

**Issue by khaliqgant** [NangoHQ/nango#611]
See #610. Add an API endpoint that returns the log information for the activity tab. This gathers the well structure log file and sends back the gathered data. Other requirements

- [x] Truncation after `n` days
- [ ] Endpoint to clear a log row
- [x] Pagination or infinite scrolling for the logs

**Comment by bastienbeurier** [comment]
Are these the follow up tasks to the Activity tab?

**Comment by khaliqgant** [comment]
> Are these the follow up tasks to the Activity tab?

Yes, exactly! I'll update the title

**Comment by khaliqgant** [comment]
Not sure if "Endpoint to clear a log row" is really needed
