### ISSUE TITLE
Better support for SSO/OAuth login with Nango

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#617]
Nango's OAuth features were built to get access to APIs which use OAuth. Single Sign on/login through OAuth was not really considered in the design of the frontend SDK.
This focus will probably always remain: There are a lot of specialized open-source libraries and services for SSO out there.

But there is a legitimate use case for SSO with Nango:
For some services the integration is so central that it makes sense to offer SSO with the API as well. E.g. Calendly does this with Google OAuth (you directly authorize calendar access when you sign up), a Nango user does this with Spotify access etc.
For these cases it would be great if Nango also had an SSO-friendly frontend API/SDK.

The main issue currently is that we ask you for the `CONNECTION-ID` in the `nango.auth(` frontend call. A connection or user-id is not known in the SSO case. Instead, we should provide a way to start the OAuth flow without an ID upfront and then report the authorized user back to the frontend.

If you have an SSO use case for Nango please feel free to leave a comment with details on your use case. This will help us prioritize this issue and build an API that works for your case as well.

**Comment by metcoder95** [comment]
I've seen several tickets regarding fragmented support for the OAuth2 spec, what are the current ones supported, and there are other flows that might be considered?

For now, it seems:
- implicit-flow seems to be missed
- OIDC (seems the case for calendly)
- any other?

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker

**Comment by oytuntez** [comment]
This would definitely relieve our current efforts to consolidate integrations and identity management.
