### ISSUE TITLE
Add banner about unified API to cloud

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#636]
Nango Cloud by default currently only supports OAuth + proxy API requests.
For new users signing up to cloud this can be unclear.

Suggestion: Add a banner to the Integrations tab on unified API and how to get access to the beta.

Title: Looking to use or build your own unified API?
Body text: The Nanago unified API and platform to build your own custom integrations is in private beta for now. Please reach out on the [Slack community](https://nango.dev/slack) or [schedule a quick call](https://nango.dev/chat) for a preview and to get access.

@bastienbeurier offered to do a mockup.

**Comment by bastienbeurier** [comment]
I propose to use this pre-made one from Tailwind! 

![Screenshot 2023-05-15 at 13 49 25](https://github.com/NangoHQ/nango/assets/2560456/a3741154-2ab2-47b6-bb17-2a6c76f35370)

**Comment by bastienbeurier** [comment]
Here's how it could look in the app.

Also I made the text shorter to fit a single-line banner with a unique CTA (I kept the Calendly link but can change it).

Planning to use the browser's local storage to persist the dismiss setting.

<img width="1512" alt="Screenshot 2023-05-15 at 14 14 51" src="https://github.com/NangoHQ/nango/assets/2560456/77838bff-ccad-4ae8-88b3-c68f0b82cc0d">

**Comment by rguldener** [comment]
Works for me but I would change the CTA to this:

```
mailto:hello@nango.dev?subject=Unified%20API%20Beta&body=Hello%2C%0D%0A%0D%0AI%20would%20like%20to%20test%20the%20Nango%20unified%20API.%20Can%20you%20please%20give%20me%20access%3F%0D%0A%0D%0AThanks%20%26%20best%2C%0D%0A%5BYOUR%20NAME%5D
```

I think less friction with a pre-written email rather than a call booking.

![image](https://github.com/NangoHQ/nango/assets/682011/efffe536-32c4-4c28-bb7b-69b4b1593a62)

**Comment by rguldener** [comment]
Also I think there is a typo in the banner: Interested in **the** Nango Unified API? Join the Beta ->

**Comment by bastienbeurier** [comment]
About the mailto, the problem IMO is that it's not always reliable, e.g. if you use Gmail and have the default mac settings, you're going to be redirected to Mac's Mail app, which you don't want. Maybe a form then? Happy to reintroduce 2 CTAs if needed, I just feel 1 is generally better.

About the 'the' omission, it was intended, in the sense of that there's not a single Nango unified API, but a "Nango Unified API" product.

**Comment by rguldener** [comment]
I see. Just linking to the Slack community for the CTA then for now?
Not sure what converts better, a community link or a form.
