### ISSUE TITLE
`invalid_secret_key` error on self-hosted version with secret key

### ISSUE THREAD

**Issue by danphilibin** [NangoHQ/nango#646]
Hi there - I'm trying to use the Node SDK to get a token from a self-hosted instance secured by a secret key, and I'm getting an `invalid_secret_key` error. Upon inspecting the request headers it looks like the SDK prefixes the key in the `Authorization` header with `Bearer` (maybe because of [this line](https://github.com/NangoHQ/nango/blob/41f554e91224f18c4917102cd723853e5e6414c2/packages/node-client/lib/index.ts#L8)?) but the `AccessMiddleware` is expecting `Basic` in its non-cloud section:

https://github.com/NangoHQ/nango/blob/41f554e91224f18c4917102cd723853e5e6414c2/packages/server/lib/controllers/access.middleware.ts#L56-L60

Let me know if that seems right or if I'm misreading the code.

Package version: `"@nangohq/node": "^0.17.0",`
Server version: `0.17.1`

**Comment by bastienbeurier** [comment]
Sorry for this @danphilibin, this is the same problem reported on this [slack community thread](https://nango-community.slack.com/archives/C04ABR352H0/p1684969595316799). This should be fixed with the `0.17.1` version of the Node backend SDK (`@nangohq/node`).
