### ISSUE TITLE
Gong

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#648]
Requested on the [community](https://nango-community.slack.com/archives/C03QBHSMPUM/p1684689871498969?thread_ts=1684494980.766939&cid=C03QBHSMPUM).

**Comment by rguldener** [comment]
Gong supports both Basic auth and OAuth2.
For now I added support for Basic auth with the `gong` provider. This is easier for new people to get started to build integrations.

Gong API docs: https://app.gong.io/settings/api/documentation#overview

We can add OAuth2 support in the future:
* Gong supports OAuth2, documented here: https://help.gong.io/hc/en-us/articles/13944551222157-Create-an-app-for-Gong
* But to create a Gong OAuth2 app you need a Gong account and the integration needs to be approved by their integrations team.
