### ISSUE TITLE
APIs don't seem to be working

### ISSUE THREAD

**Issue by KShivendu** [NangoHQ/nango#649]
Hi, I was trying out the APIs from the [API Reference](https://docs.nango.dev/api-reference/integration/list)

I passed my secret key in the Bearer field but the response turned out to be empty `""`. 

I also tried the curl command generated by the docs:
```bash
curl --request GET \
  --url https://app.nango.com/config \
  --header 'Authorization: Bearer XXX-XXX-XXX-XXX-XXX'
```

But it was also not working. Not sure what's happening. Am I missing something here?

**Comment by bastienbeurier** [comment]
@KShivendu I'm sorry for the inconvenience. I made an error in the docs, the domain is actually `api.nango.dev`, not `app.nango.com`. Will fix asap.

**Comment by bastienbeurier** [comment]
The updated docs are live, just verified that it works.
