### ISSUE TITLE
NPM Front end package has an issue

### ISSUE THREAD

**Issue by csnelsonchu** [NangoHQ/nango#655]
Not able to run the frontend package on my local machine
I tested at https://npm.runkit.com/%40nangohq%2Ffrontend and seeing this same issue as well.
Any idea how to resolve this?
```
Error: require() of ES Module /app/available_modules/1685841359000/@nangohq/frontend/dist/index.js from /app/index.js not supported.
Instead change the require of /app/available_modules/1685841359000/@nangohq/frontend/dist/index.js in /app/index.js to a dynamic import() which is available in all CommonJS modules.
A stack trace for this error could not be retrieved because stack was already called.
```

**Comment by rguldener** [comment]
Sorry you are running into this @csnelsonchu.

What is the setting of `type` in your `package.json`?
Nango makes use of the (newer) ES modules system, which is not compatible with the old `require()`/commonjs based node imports. It sounds like this error is related to this?

You can either set `type` to `'module'` in your package.json (but then all imports must be with ES modules) or you can take a look at the workarounds here: https://stackoverflow.com/questions/70396400/how-to-use-es6-modules-in-commonjs

**Comment by bastienbeurier** [comment]
Closing this until it resurfaces
