### ISSUE TITLE
Support API Request: Grinding Gear Games Path of Exile API

### ISSUE THREAD

**Issue by HiMarioLopez** [NangoHQ/nango#665]
From GGG's PoE API docs:

# Authorization

Almost all of Path of Exile's developer APIs require authorization of an existing Path of Exile account to use. This helps us enforce fair rate-limits as well as having a point of contact if anything goes wrong.

For this purpose we use an implementation of the OAuth 2.0 framework. This document will describe how to generate access tokens for users using your application's credentials.

https://www.pathofexile.com/developer/docs/authorization

## OAuth Server Endpoints

- `/oauth/authorize`: Authorization page for obtaining user consent.
- `/oauth/token`: Endpoint for creating tokens.
- `/oauth/token/revoke` (requires the oauth:revoke scope): Endpoint for revoking tokens.
- `/oauth/token/introspect` (requires the oauth:introspect scope): Endpoint for checking tokens.

## Client Types

OAuth 2.0 defines two client types which we support in different ways. The vast majority of applications should use a Confidential Client.

### Confidential Clients

A confidential client is backend by a secure server controlled by the application owner. These clients:

- May use any of the available grant types. Any redirect URIs must point to a domain controlled by the application owner.
- Have access tokens that last for 28 days and refresh tokens that last for 90 days.
- Usually have individual rate-limits per client.

### Public Clients

A public client is one without a method of securely storing any credentials. The most common example of this is an application that runs on the user's desktop. These clients:

- Must only use the [Authorization Code (with PKCE)](https://www.pathofexile.com/developer/docs/authorization#authorization_code) grant type and must use a local redirect URI.
- Cannot use any service:* scopes.
- Have access tokens that last for 10 hours and refresh tokens that last for 7 days.
- Have shared rate-limits between all other public clients.
- Display a warning message to the end user when authorizing; stating that the authenticity of the request is unverifiable.

**Comment by rguldener** [comment]
@HiMarioLopez thanks for opening the issue!

At first glance looks like this should be compatible with Nango (we are what they call a "Confidential Client"). If you want to contribute it you can find instructions here: https://docs.nango.dev/contribute/nango-auth

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
