### ISSUE TITLE
Support JWT grant OAuth 

### ISSUE THREAD

**Issue by nilquera** [NangoHQ/nango#668]
We want to integrate with DocuSign OAuth through Nango. We want to use [**JWT code grant** OAuth](https://developers.docusign.com/platform/auth/jwt/) (instead of the conventional auth code grant OAuth). However, Nango doesn't support JWT code grant (only normal OAuth).

## JWT Code OAuth
JWT Code OAuth differs from the conventional OAuth by isolating the grant consent process with the access token retrieval. In the grant consent process, the user simply grants consent to an app that wants to act on his behalf. When the moment to impersonate the user arrives, the backend builds up a JWT (using the app's client id & the user id to impersonate) & exchanges it for the access token. As soon as the access token expires, you get a new one by building a new JWT. You can repeat this process without limits, hence the benefits of JWT (no need to get the user involved again).

### Integration
When adding the integration, we should add a way of marking it a jwt code flow. This will affect the connection creation and the access token retrieval.

### Connection
We would assume the user has already granted consent. Adding a connection would be just a matter of associating the `user id` in the provider with the `Integration Unique Key`, and giving it a `connection id`. Adding the connection wouldn't automatically get a fresh token.

### Access Token
On first try, the server would build a jwt containing:
- `client id` from the integration provider.
- `user id` associated to the `connection id` defined before.
- expiration, oauth server url & oauth scopes
The given access token would be stored together with the expiration date given in the response.
Subsequent retrievals of the access token would verify the expiration of it. If expired, it would build a new JWT and get a fresh access token.

Please, leave your feedback if you think this doesn't make much sense or is not actually doable 😄

**Comment by bastienbeurier** [comment]
@seanmizen @madalinbartos-gbc @PeterCockcroft do you also want to use DocuSign or some other API? I just want to make sure your APIs are supported as we build this.

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
