### ISSUE TITLE
Retry Nango webhooks when error response

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#687]
From a user: 
> Do you plan to add a retry policy for Nango webhook when the response isn’t 2xx? :thinking_face: We see this important not to lose any data updates once in production.

**Comment by richardt-engineb** [comment]
Feels like (outgoing) webhooks are just as "how hard could it be?" as OAuth integration is!  Might be worth looking at one of the many open source webhooks-as-a-service options that are available: https://www.svix.com/open-source-webhook-service/, https://getconvoy.io/ or similar?

To be honest, I've never used them though, so I can't say either way if they actually work as well as they claim to or not.
