### ISSUE TITLE
UI improvements for syncs tab

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#714]
A few small improvements for the new syncs tab:
- Show description at the top (people may not know what it shows)
- Show version number in a column: Much easier to see and spot discrepancies this way
- I would rename last modified to last deployed (since this is what it is, or not?)

We might also have a naming issue with the "Sync" tab in the connection. The two things are different but we currently call them the same thing.
We could call the Syncs tab "Sync scripts" and the tab in the connection "Syncs"? Or maybe we want even more distinct names.

![image](https://github.com/NangoHQ/nango/assets/682011/4dc7afd6-13cd-4a6d-add9-03e7afb783a1)

**Comment by PieterDePauw** [comment]
It can also be hard sometimes to navigate the current UI, mainly because it is not really easy to see "where you are" in the structure. It is also not very intuitive from which pages users can access other pages / resources.
