### ISSUE TITLE
Clicking button "Sync" from a Connection triggers 2 Activities

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#716]
Happened to @rguldener and I separately cc @khaliqgant

**Comment by rguldener** [comment]
In case you need to reproduce, happens 100% of the time on cloud for me currently.

**Comment by khaliqgant** [comment]
This is intended behavior. Clicking a sync command is an action and is logged as an activity. In addition whatever that action is, is also logged as an activity. 


So starting a sync would trigger two activities.

**Comment by rguldener** [comment]
Ah I see!
Makes sense in that context and I see the value of logging actions on syncs as well, they could get triggered by the SDK or API.

I think in this case it would be good to make actions on syncs a different category of activity log entry (different name, e.g. "Sync action", and maybe different icon).

What do you think @bastienbeurier ?
