### ISSUE TITLE
Support Google Service Accounts in Nango (JWT OAuth flow)

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#731]
Google Service accounts let Google workspace admins grant certain scopes for entire domains to an external app.

There are two steps involved:
- The app developer has to setup a service account in Google Cloud
- A Google workspace administrator has to enable the service account for their domain(s). This is a manual process in the Google workspace admin and cannot be done with a normal OAuth flow.

Behind the scenes the process seems to use the JWT authorization flow of the OAuth 2 protocol.

Relevant Google docs:
- [Docs for Google workspace admins on how to approve Service Accounts](https://apps.google.com/supportwidget/articlehome?hl=en&article_url=https%3A%2F%2Fsupport.google.com%2Fa%2Fanswer%2F162106%3Fhl%3Den&assistant_id=generic-unu&product_context=162106&product_name=UnuFlow&trigger_context=a)
- [Google Auth docs on how to obtain access tokens with service accounts](https://developers.google.com/identity/protocols/oauth2/service-account#httprest)

Initial notes & questions for an implementation:
- The service account credentials are still a `client_id` and `client_secret`, as well as a list of scopes (although these have to be entered manually by the Google workspace admin as well). In addition there is public/private key pair involved -> Maybe this could be setup as a different kind of Integration in Nango?
- The token refresh flow also uses the JWT flow
- The end-user should probably see some information about the client id & scope in the app's interface and be able to say "I installed it". Ideally we could then check in real-time whether this installation worked & store the authorized domain(s) as Connection(s) in Nango? Maybe Google has an endpoint you can query to get a list of all authorized workspace domain(s)?
   - This functionality could also be cool for API keys: User enters api key, Nango immediately checks if the key works before storing it with the connection (?)
- I have seen other APIs also use the JWT flow, but so far none of them have been relevant for Nango. Other APIs also have service accounts, e.g. Microsoft, but they use a normal authorization code flow for authorization.

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
