### ISSUE TITLE
Customer-facing Slack alerts on errors

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#774]
Could be through Slack, Email, webhook, PagerDuty, etc. From a discussion with Tyler from Tennr.

Maybe we could also deactivate syncs that fail constantly, and send a notification. This would allow to keep the number of failing syncs low on the platform and detect the problematic ones more easily.

**Comment by khaliqgant** [comment]
@bastienbeurier didn't realize this was open already, sorry. Closing as it is a duplicate of #1192
