### ISSUE TITLE
Upserts: Handling records deleted on the API (no longer returned)

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#78]
Currently when Nango does a refresh it fetches all the records from the remote, checks if they exist in the DB (using the `unique_key`) and depending on that updates the existing record or adds a new one.

This means that if a record has been deleted on the remote, and hence no longer gets returned in the response, we don't do anything and just keep the old record around. This is one possible way to handle this scenario, another would be to also delete the record in the DB. A third option would be to mark it as deleted first and then remove it in a subsequent run (this would give the application a chance to act on the record before it gets removed).

We are not sure yet which behaviour is best, if you have a use case for this please leave a comment here so we can gather them.

**Comment by lgo** [comment]
I'd love this for a personal project I'm doing. Specifically, I'm writing an app to connect Splitwise (group expense splitting) and YouNeedABudget (budgeting app) for a web app to help link and manage expenses entered in Splitwise to bank transactions in YNAB.

I need to pick up deletions from either app to update the local state and action it. For example, if some data for an expense on Splitwise is deleted, I would want to push an update to the associated data in YNAB. If some data is deleted from YNAB that's linked to Splitwise, I'd update local state and surface it on the web app.

For this use-case, either deleting the record or adding a marker would work but markers would be far more usable. With markers, I imagine I could write a simple cron that scans records with the delete marker to action them. If the records were outright deleted I'd need to do a full scan of records and check references.

**Comment by timrogers** [comment]
I think it would be good to offer the options of (a) deleting the record and (b) touching a `deleted_at` (or similar) timestamp column.

**Comment by bastienbeurier** [comment]
Understood, that's pretty high on the priority list since capturing deletions is a requirement for many use-cases. 

This week is focused on providing callbacks on job completion + simplifying OAuth in Nango. I'll focus on this in the two coming weeks.
