### ISSUE TITLE
Duplicate syncs & schedules in DB

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#791]
As discussed this morning with Khaliq, we noticed that the `_nango_syncs` table has duplicate `nango_connection_id`/`name` pairs, each having a corresponding `_nang_sync_schedules` row (that has `RUNNING` status).

We should investigate: 
- Why these duplicates are created
- If that has impact on customers
- How to prevent future duplicates and mitigate custom impact

Also with this issue dev creds should be encrypted

**Comment by khaliqgant** [comment]
> Why these duplicates are created

If a pre existing connection id is created again and goes through the oauth flow the sync will be initiated again

> If that has impact on customers

No major impact except that sync data is overwritten and their connection sync tab will have duplicates.

> How to prevent future duplicates and mitigate customer impact

Prevent further duplicates with https://github.com/NangoHQ/nango/pull/796. We should write a script that removes dupes and deletes the sync and duplicate schedules and then add the migration that enforced uniqueness at the db level 

@bastienbeurier

**Comment by bastienbeurier** [comment]
Thank you for getting to the bottom of this @khaliqgant. The script will also help with having precise BI!
