### ISSUE TITLE
Dry run isn't always dry

### ISSUE THREAD

**Issue by khaliqgant** [NangoHQ/nango#799]
* Some commands would actually go through unexpectedly 
* `getConnection` would hit the server which I think is fine
* `setFieldMapping` shouldn't hit the server
* All proxy calls except `get` should not actually get called

Agree on the above @bastienbeurier ?

**Comment by bastienbeurier** [comment]
As discussed on Slack, I think that it's okay for now to keep the side effects. I think that the proxy calls should definitely go through, since that's what we're testing with `dryrun` most of the time. `setFieldMapping` is more of an edge case. 

Let's see if anybody complains about it!
