### ISSUE TITLE
Sentry improvements

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#801]
[Sentry is only active for Nango Cloud]

# Improve identification

We have legacy code to map events/exceptions to users. For each event, we should attach a user with: 
- User ID
- Email
- Account ID

I think the main `id` that Sentry uses to evaluate the # of affected users should be the Account ID (because some calls don't have a user ID, e.g. API calls which use the secret/public keys). 

That will help searching all errors for a given customer using the Explore tab and can greatly improve our support process. E.g.: we should be able to easily list all the failed syncs for a given customer and given integration, to dig in the stack traces.

# Tags 

## Environments

We should leverage tags for environments. That way we can exclude events/exceptions of the `dev` env from the dashboards, metrics and issues. 

## Platform vs. Customer Events

In Sentry, exceptions are coalesced in issues, which then need to be resolved. Today, we have issues related to platform problems (some integration breaks for all customers), and some other related to [customer problems](https://nango.sentry.io/issues/4260988803/?project=4504688963682304&query=is%3Aunresolved&referrer=issue-stream&stream_index=0) (e.g. wrong integration configuration, etc.). 

It's not so easy to differentiate the two, because:
- the difference can be subjective
- sometimes we catch many different exception types in the same `catch` block, which makes it hard to differentiate platform vs customers

But whenever we can, we should apply tags to differentiate the two. So that we can: 
1. Exclude customer exceptions from the Issues tab
2. Focus on customer exceptions when provider support

# Metrics 

We can leverage Sentry's Explore and Dashboard tabs to monitor metrics. IMO, the first metrics we should track should be: 
- Nbr of successful sync runs per hour 
- Nbr of failed sync runs per hour

This will allow us to have confidence with our deployments (that syncs are not going from successful to failed post-deploy).

For this, we can leverage the `sentry.captureEvent` call (instead of `captureException`):
```js
sentry.captureEvent({
    message: message,
    user: {
        id: `${accountId}`,
        email: email,
        userId: userId
    }
});
```

For sync failures, we should capture some generous metadata to help us support customers with failing syncs, e.g.: 
- provider config key
- provider
- sync name
- etc.

Sync failures/successes are typical a `customer` event (vs. `platform`).

**Comment by khaliqgant** [comment]
```
export interface Event {
    event_id?: string;
    message?: string;
    timestamp?: number;
    start_timestamp?: number;
    level?: Severity | SeverityLevel;
    platform?: string;
    logger?: string;
    server_name?: string;
    release?: string;
    dist?: string;
    environment?: string;
    sdk?: SdkInfo;
    request?: Request;
    transaction?: string;
    modules?: {
        [key: string]: string;
    };
    fingerprint?: string[];
    exception?: {
        values?: Exception[];
    };
    breadcrumbs?: Breadcrumb[];
    contexts?: Contexts;
    tags?: {
        [key: string]: Primitive;
    };
    extra?: Extras;
    user?: User;
    type?: EventType;
    spans?: Span[];
    measurements?: Measurements;
    debug_meta?: DebugMeta;
    sdkProcessingMetadata?: {
        [key: string]: any;
    };
    transaction_info?: {
        source: TransactionSource;
    };
    threads?: {
        values: Thread[];
    };
}
```

```
export declare function captureEvent(event: Event, hint?: EventHint): ReturnType<Hub['captureEvent']>;
```
