### ISSUE TITLE
Fix broken links in the docs

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#810]
Upgrade mintlify then run `mintlify broken-links`.
Currently there are 243, mostly because there are a few on every API page.

**Comment by Bhardwaj-Himanshu** [comment]
Hi @rguldener, as I am new to the community could you please eleborate a bit over on what is mintlify and how to upgrade it?
-I am assuming it is a command/bot to search up for things inside the program
-cause fixing broken links should be easy enough, just locating them would take time

Let me know if you are working on something and if I could be of any help into this.
Also, I had some problems `setting up the project locally`, the conversation of which is over slack channel in the link-https://nango-community.slack.com/archives/C051VRNQVJM/p1690097994975229
Thanks

**Comment by bastienbeurier** [comment]
Fixed with https://github.com/NangoHQ/nango/commit/74872c505703b7bdef40435373b89714d78a765c

Hi @Bhardwaj-Himanshu , Mintlify is our docs provider (mintlify.com). You can find instructions on how to use it on their docs!

**Comment by Bhardwaj-Himanshu** [comment]
Ah thanks for the info @bastienbeurier
