### ISSUE TITLE
Delete a connection from the node SDK

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#825]
From a [request](https://nango-community.slack.com/archives/C04ABR352H0/p1690213502802839?thread_ts=1690142501.422079&cid=C04ABR352H0) on the community: 

> Would be great to have a deleteConnection method on the Node SDK. They programmatically get created when a user goes through the oauth flow in our app. We’d want the user to be able to remove the connection as well.

- [x] Integration tests for node SDK and HTTP endpoint with type agreement https://github.com/NangoHQ/nango/issues/273

**Comment by rguldener** [comment]
This already exists on the REST API, it is just not expose in the node SDK I think?
https://docs.nango.dev/api-reference/connection/delete

Or is this for something different?
