### ISSUE TITLE
Document `init` `dev` `generate` better in docs

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#828]
`init` is the 1st (optional) command you run and it: 
- Creates `nango-integrations`
- Adds files for the example Github integration
- Creates the corresponding `models.ts` 
- Does not create a `dist/*` folder

`dev` is the fundamental and mandatory command to dev on Nango: 
- Watches over `nango.yaml` to generate the `models.ts` file (both model interfaces + sync helper classes)
- Watches over sync scripts to build the `dist/*` folder
- Should not generate nor edit sync script .ts files

`generate` is an optional helper command to:
- generates initial scaffolds for sync scripts (once)
- to do so, it also needs to (redundantly with `dev`) generate the `models.ts` file

**Comment by Bhardwaj-Himanshu** [comment]
Hi @bastienbeurier Could I help you in any kind over documenting this? Or create a PR for the same?

**Comment by bastienbeurier** [comment]
Resolved by https://github.com/NangoHQ/nango/commit/e1c4e953daef381bb9ecb563feea62790f924102
