### ISSUE TITLE
Cap sync run memory usage & run time

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#830]
Recently, a customer deployed a sync with an infinite looped. I ran for 30mins and crashed our worker. 

We should cap runs in a way that prevents this type of issue. Customers are going to make mistake, some people are going to be malicious, we should account for the fact that arbitrary code can be deployed to Nango and limit the negative consequences it can have. 

My first idea was to limit memory usage & run time. Should we limit anything else (CPU usage, etc.)?

**Comment by khaliqgant** [comment]
Capping memory usage in #790 at 500MB. Run time is capped at 90 minutes via https://github.com/NangoHQ/nango/blob/master/packages/worker/lib/workflows.ts#L5. Closing this due to it being a duplicate of #790 as it will be tackled there.
