### ISSUE TITLE
"Invalid JSON" token refresh error with some HubSpot connections

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#882]
A user reported on the Nango community that for some Connection IDs he gets an invalid JSON error from HubSpot on token refresh.
![image](https://github.com/NangoHQ/nango/assets/682011/4c311d74-be59-4f31-bcf1-4f0a0334ba85)

He is using Nango cloud, full details on the affected connection and the account is available here (only works for Nango employees): https://nango-community.slack.com/archives/C04S10A3V25/p1691416955037619

**Comment by khaliqgant** [comment]
Possibly related: https://github.com/lelylan/simple-oauth2/issues/279

**Comment by khaliqgant** [comment]
Also potentially related https://nango.sentry.io/issues/4380568962/?project=4504688963682304&query=is%3Aunresolved&referrer=issue-stream&stream_index=3

Log line: https://my.papertrailapp.com/systems/production-server/events?q=The+content-type+is+not+JSON+compatible&focus=1625177350780194858&selected=1625177350780194858

**Comment by khaliqgant** [comment]
Intermittent issue that the user said couldn't reproduce.
