### ISSUE TITLE
Feat: Wix integration

### ISSUE THREAD

**Issue by HelloAlexPan** [NangoHQ/nango#884]
[Opening an issue to integrate the Wix API](https://dev.wix.com/docs/rest/articles/getting-started/overview)

**Comment by rguldener** [comment]
Thanks for opening the issue @HelloAlexPan !

Is this urgent for you?
If so, you could probably add support for it to Nango with the guide here: https://docs.nango.dev/contribute

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
