### ISSUE TITLE
Trigger one off sync improvements

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#891]
**Optional triggering of specific syncs**
[The API](https://docs.nango.dev/api-reference/sync/trigger) should take an optional body of a list of syncs to trigger:

```json
["sync-1", "sync-2"]
```

`sync-1` and `sync-2` here would be the name of the sync scripts to trigger.
If no body is passed the request should trigger a one-off sync for all syncs.

**Update & document one-off syncs for the node SDK**
This option should also be exposed to the node SDK.

The one-off sync trigger should also be documented on the node SDK docs.

**Comment by khaliqgant** [comment]
The optional body is instead:
```
{ 
    "syncs": ["g-org-unit-sync"]
}
```
