### ISSUE TITLE
OAuth & Requests: Add support for APIs with dynamic URLs

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#9]
## Objective
The current implementation of the Integrations configuration (both for auth and requests -> api_base_url) assumes that the URLs are static.

However, there are a good number of APIs where that URL depends on a parameter of the user's account, e.g. for shopify the API & OAuth base URLs start with `https://{shop}.myshopify.com`. Some examples:
- Salesforce has fixed URLs for OAuth but a "tenant specific" base URL for the API
- BambooHR and Pipedrive have the same model as Shopify with different base URLs per customer
- Zoho Books has different domains depending on the data center of the customer: https://www.zoho.com/books/api/v3/oauth/#overview
- Zendesk chat requires the subdomain of the customer to be passed in during the Authorization step of OAuth

There are probably at least 2 use cases hidden here:
1. Parametrize the OAuth URLs/process
2. Parametrize the request api_base_url 

We should support these cases by having an additional layer of configuration parameters that can be accessed in these values of the integration configuration.

**Comment by bastienbeurier** [comment]
Belongs to the previous product, should probably be part of Pizzly's issues now. Let's reopen if needed.
