### ISSUE TITLE
Allow pause/restart of syncs per connection with API & SDK

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#913]
Currently you can pause/restart syncs per connection in the dashboard. But we do not expose this is in the API and the SDK.

A user is requesting that we expose this in the API and SDK as well.

![image](https://github.com/NangoHQ/nango/assets/682011/fa259eb7-ac8c-4d2f-acd1-738636caf411)

---

# Implementation Notes
Note that docs still need updating

**Comment by rguldener** [comment]
Use-cases heard so far:
- Not every user wants/needs every sync: E.g. only cares about contacts, but not leads.
- Want to not use up sync runtime for data that is not required/used

At least 2 customers asked for this in the community.

**Comment by khaliqgant** [comment]
Pausing a sync should also pause the sync if is actively running. At the moment the pause only pauses _future_ runs of that sync

**Comment by bastienbeurier** [comment]
Duplicate of #990
