### ISSUE TITLE
`fetchData` call fails if no object returned at end

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#918]
As [reported on the community](https://nango-community.slack.com/archives/C04ABR352H0/p1692012783794349): `nango dryrun` throws an error if one tries to dryrun a script which doesn't return anything at the end.
The syncs also fail on Nango cloud for the same reason.

```
export default async function fetchData(
  nango: NangoSync
): Promise<void> {

// Function

}
```

Workaround for now:
Use the old format with the `return { 'Model': [] }`

Since we want to move to this format this should be fixed :)

**Comment by khaliqgant** [comment]
Requires an undefined check here: https://github.com/NangoHQ/nango/blob/master/packages/shared/lib/services/sync/run.service.ts#L230
```
if (userDefinedResults &&
```

Also need to signal that the script is finished ending so the log can be terminated and the webhook can be sent 

Related to #912
