### ISSUE TITLE
[ Missing ] docker self deploy for 3rd party cloud instances.

### ISSUE THREAD

**Issue by shreyas-lyzr** [NangoHQ/nango#920]
![image](https://github.com/NangoHQ/nango/assets/141219160/9e05fa45-b8cc-4d51-be99-d951760a9228)

**Comment by bastienbeurier** [comment]
@shreyas-lyzr with the recent complexification of the platform, we haven't yet invested into providing a streamlined self-hosting experience for the sync part of Nango. We will let you know as soon as we have a timeline for this. In the meantime, I would use the Cloud version (or the self-hosting for Nango auth only).
