### ISSUE TITLE
Disable Autofill

### ISSUE THREAD

**Issue by roopeshsn** [NangoHQ/nango#929]
It's annoying that every time google autofills my saved email and password into client id and secret.

Solution: https://gist.github.com/niksumeiko/360164708c3b326bd1c8

![screenshot-app nango dev-2023 08 24-17_37_56](https://github.com/NangoHQ/nango/assets/70762571/38ece480-a82b-4617-be22-482931d341dc)

**Comment by bastienbeurier** [comment]
@roopeshsn indeed, this is annoying. we'll tackle this shortly.

**Comment by bastienbeurier** [comment]
Still experienced by me and can be seen in session recordings.
