### ISSUE TITLE
Wrong "Update Connection Metadata" API ref

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#939]
Flagged on the community: 

> Looking at the code, the endpoint also checks for a “Provider-Config-Key” header, which works. So I guess the documentation need to be updated

The [reference](https://docs.nango.dev/api-reference/connection/set-metadata) is indeed wrong.

**Comment by blair49** [comment]
Hi @bastienbeurier ,
It seems like this is already implemented as the "Provider-Config-Key" header is now marked as required in the documentation. Or I am missing something?
![image](https://github.com/NangoHQ/nango/assets/31095601/7b47e4b4-d38f-4fb8-bb1a-c093b4836d6b)

**Comment by bastienbeurier** [comment]
That's right, thanks for flagging, I'll close this then!
