### ISSUE TITLE
Discogs

### ISSUE THREAD

**Issue by ardsh0ck** [NangoHQ/nango#942]
Hi guys. I would like to get integration with [Discogs API](https://www.discogs.com/developers).

**Comment by bastienbeurier** [comment]
Hi @ardsh0ck, Discogs is indeed compatible with Nango (json-based API, standard auth: OAuth or API Key).

We have a dedicated [guide](https://docs.nango.dev/contribute) to contribute new APIs.

We do offer to support new APIs with a fast turnaround for customers. If you wish to become one, the best would be to schedule a [call](nango.dev/call) to discuss your use-case with more details.

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
