### ISSUE TITLE
Nango Sync are not working as per the schedules

### ISSUE THREAD

**Issue by jayadeep-saaslabs** [NangoHQ/nango#963]
Hosted the Nango server, worker and temporal in GKE, Postgres db in cloud sql and all are up and running without any restarts. But Nango Sync for the integrations are not working in the sync section of a connection showing "No Syncs yet" is mentioned. Attaching the screenshot of the sync section of a sample github issues integrations for your reference.
<img width="1680" alt="Screenshot 2023-09-05 at 10 41 06 AM" src="https://github.com/NangoHQ/nango/assets/126876165/f273161d-0233-4d0e-ac15-bc53eade2985">

**Comment by khaliqgant** [comment]
Sorry for the delay here but syncs are not available for self hosted https://docs.nango.dev/cloud
