### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [NangoHQ/nango#976]
Describe the bug
Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

Steps To Reproduce
Scroll to footer section and see twitter old logo

Expected behavior
Twitter logo should be changed to X

Screenshot
<img width="872" alt="Screenshot 2023-09-07 184131" src="https://github.com/NangoHQ/nango/assets/91591901/53627016-1487-418c-aa52-f9368730ac0e">

Additional Context
Won't change anything in the code as such would replace the twitter-logo with a new file. No code will be touched.

@mdp 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
