### ISSUE TITLE
401 error on access token request

### ISSUE THREAD

**Issue by bhaktatejas922** [NangoHQ/nango#988]
<img width="1140" alt="Screenshot 2023-09-08 at 9 37 16 PM" src="https://github.com/NangoHQ/nango/assets/26863466/6849d03a-28b6-4bea-8d37-fd3da298ea9a">

We could not retrieve and/or refresh your access token due to the following error: The external API returned an error when trying to refresh the access token. Please try again later. { "external_message": "Response Error: 401 Unauthorized", "external_request_details": { "statusCode": 401, "payload": { "statusCode": 401, "error": "Unauthorized", "message": "Response Error: 401 Unauthorized" }, "headers": {} }, "dataMessage": { "error": "unauthorized_client", "error_description": "Unauthorized" } }

I recently switched my google client id/secret and now I get this error. Not sure why, but I suspect something is cached on the api.nango.dev side

**Comment by bhaktatejas922** [comment]
Even stranger, the initial auth shows success in the activity logs, but subsequent requests show the error shown ^

**Comment by bhaktatejas922** [comment]
I think I confirmed its something on the nango side
1) when I test a new connection with a random connection ID, it works in the nango UI
2) when I test a new connection with a connection ID I had in the past, it breaks (even though I deleted it) in the nango UI
I suspect deleting connections in the nango UI doesn’t actually fully delete everything.

 If there’s some cache you can clear for me that would be great

**Comment by bastienbeurier** [comment]
@khaliqgant this one is solved by the #1016 PR?

**Comment by khaliqgant** [comment]
> @khaliqgant this one is solved by the #1016 PR?

Yeah should be.
