### ISSUE TITLE
Sync-level attribute & programmatic management

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#990]
A developer has a use-case where: 
- Users can enable-disable individual syncs
- Each sync has some specific fields that should be mapped to user-specific fields in their external systems. Instead of storing these fields in the developer's DB, the developer asks to store them in some sort of sync metadata object (specific to a sync, but for all connections).

The question is how should this metadata be set? 
- In the `nango.yaml` 
- Via API / SDK 
- In the dashboard

# Thoughts about metadata

| | API/SDK | Dashboard | `nango.yaml` |
|-|-|-|-|
| Needs to handle complexity & dynamic updates | ✅ | ❌ | ❌ |
| Needs history & review & deploy with rest of code) | ✅ | ❌ | ✅ |
| Needs to be strongly tied to script logic | ❌ | ❌ | ✅ |
| Needs fast setup | ❌ | ✅ | ✅ |
| Needs fast-pace changes & collab | ❌ | ✅ | ❌ |
| Needs helpful UI | ❌ | ✅ | ❌ |
| Needs to be secret/untracked | ❌ | ✅ | ❌ |
| Needs to be done by non-technical people | ❌ | ✅ | ❌ |

As a result, I think that sync-level config should live in `nango.yaml`, because:
- it needs review & be deployed with the rest of the code
- it can be strongly tied to script logic
-  I think it's less a good fit for SDK/API because it won't change much (and certainly not based on end-uses, because any user-specific info should be stored in the connection metadata)

# Action items

As a result, I think we should support:

## Sync attributes

`attributes` field on the sync objet in `nango.yaml`. Should contain arbitrary json fields, including nested objects/arrays.

@hilmia what do you think of storing this in `nangol.yaml`?

## API/SDK changes

All the following changes should be reflected in our Open API specs (to reflect in the docs).

### Fetch attributes (API + SDKs)

Endpoint: GET `sync/attributes`
Query params: 
- `provider_config_key` 
- `sync_name`

### Pause sync (API + SDKs)

**For all connections**

Endpoint: POST `/sync/pause`
Body: 
- `provider_config_key`
- `sync_name`

**For selected connection**

Endpoint: POST `/sync/pause/{connection_id}`
Body: 
- `provider_config_key`
- `sync_name`

### Start sync (API + SDKs)

Like pause with endpoint POST `sync/start...`

### Trigger sync (API + SDKs) 

Like pause with endpoint POST `sync/trigger...`
The trigger endpoint already exists (for specific connections). I'm not a fan of specifying parameters in the headers (cf. #972). Maybe we can deprecate it?

**Comment by hilmia** [comment]
Storing it in the nangol.yaml sounds good, will be great for integration templates as well

**Comment by khaliqgant** [comment]
@bastienbeurier let's discuss this one tomorrow. It is similar to https://github.com/NangoHQ/nango/issues/913
