### ISSUE TITLE
`nango.yaml` setting for activating syncs automatically vs programmatically

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#992]
When metadata is required to run a sync, it doesn't make sense that the sync should start running upon connection creation. This requires to write some specific logic in the sync to make it abort if the metadata is not there (and then the sync status is not reflected on the dashboard + shown as failed). 

Instead, we should have an option in `nango.yaml` to indicate if a sync should be started automatically or programmatically (via API).

Possible names for the field `auto_start:true|false`. Default value would be `true` to map what we have now.

**Comment by khaliqgant** [comment]
@bastienbeurier getting into the weeds a bit here, but I'm thinking that the schedule is created but if auto_start is false then the sync starts off in a paused state so the sync doesn't start automatically and the schedule doesn't get kicked off either.

**Comment by bastienbeurier** [comment]
> @bastienbeurier getting into the weeds a bit here, but I'm thinking that the schedule is created but if auto_start is false then the sync starts off in a paused state so the sync doesn't start automatically and the schedule doesn't get kicked off either.

Works for me!
